# Nestor Intake GCP footprint (D-01, RESEARCH Pattern 4).
#
# Provisions, with IAM database authentication and NO stored DB credential
# anywhere (D-03/D-09/V10):
#   - a POSTGRES_16 Cloud SQL instance (IAM auth on, public IP, NO IP allowlist)
#   - the application database + the runtime SA's IAM DB user (login only)
#   - an Artifact Registry Docker repo for the backend image
#   - the least-privilege Cloud Run runtime service account (V14)
#   - the Cloud Run gen2 service (max-instances=4, D-04) + the alembic migration Job
#
# The Cloud SQL Python Connector tunnels via the Cloud SQL Admin API over TLS
# with ephemeral certs (D-03) -- so there is NO IP allowlist and the Cloud Run
# resources need NO Cloud-SQL-instance attachment flag / annotation (the
# RESEARCH anti-pattern). The only credentialed path to the DB is the runtime
# SA's IAM identity (API-01/D-09).
#
# Phase 4 (D-05a / Path B) — the SINGLE deliberate exception to the
# "NO stored DB credential anywhere" invariant above: the cross-tenant superadmin
# code path needs a DB role that satisfies 0003's `current_user = 'app_superadmin'`
# bypass predicate. Cloud SQL forbids BYPASSRLS and an IAM SA user cannot be named
# the bare literal `app_superadmin`, so this phase provisions a BUILT_IN Cloud SQL
# user named the EXACT literal `app_superadmin` whose password is generated by
# `random_password` (never a committed literal), stored ONLY in Secret Manager,
# and read at runtime by base.py::_load_superadmin_password() via a resource-scoped
# `secretAccessor` grant on that one secret. The Cloud Run env carries only the
# secret RESOURCE NAME (SUPERADMIN_DB_PASSWORD_SECRET) -- never the password value
# -- so the password never lands in IaC/state/env plaintext (T-04-16/T-04-17).

locals {
  # The IAM DB username = the runtime SA email WITHOUT the ".gserviceaccount.com"
  # suffix (Cloud SQL IAM-login convention). Used for the google_sql_user name,
  # the service DB_USER env, and the Job's DB_USER / RUNTIME_DB_USER env.
  runtime_db_user = trimsuffix(google_service_account.runtime.email, ".gserviceaccount.com")

  image = "${var.region}-docker.pkg.dev/${var.project}/${var.repo}/backend:${var.image_tag}"
}

# --------------------------------------------------------------- Cloud SQL (D-01/D-03)
# POSTGRES_16, IAM auth ON, public IP, NO authorized-networks allowlist (the
# connector tunnels via the Admin API, not an IP list -- T-02-14). deletion
# protection ON so a stray destroy cannot drop the tenant DB.
resource "google_sql_database_instance" "main" {
  name             = var.instance_name
  region           = var.region
  database_version = "POSTGRES_16"

  deletion_protection = true

  settings {
    tier = var.tier # db-custom-1-3840 -> default max_connections=100 (A4/D-04)

    # IAM database authentication -- the ONLY auth path; there is no built-in
    # DB credential to store or leak (D-03/D-09).
    database_flags {
      name  = "cloudsql.iam_authentication"
      value = "on"
    }

    ip_configuration {
      ipv4_enabled = true # public IP; the connector secures the channel (D-03).
      # Intentionally NO IP allowlist block here -- access is gated by IAM, not
      # by network range (T-02-14). Adding one is the anti-pattern we avoid.
    }
  }
}

# The application database (D-01).
resource "google_sql_database" "app" {
  name     = var.db_name
  instance = google_sql_database_instance.main.name

  # WR-06: the instance-level deletion_protection does NOT cover the database
  # object. Protect the tenant DB itself so a `terraform destroy` targeting this
  # resource (or a config change forcing its replacement) cannot silently drop the
  # `nestor` database while the instance survives. deletion_protection guards the
  # provider-level destroy; prevent_destroy is the Terraform-core backstop.
  deletion_protection = true

  lifecycle {
    prevent_destroy = true
  }
}

# The runtime SA's IAM DB user. type=CLOUD_IAM_SERVICE_ACCOUNT grants LOGIN ONLY
# -- zero Postgres privileges by default (Pitfall 3). The 0005 migration GRANTs
# it the space-scoped privilege set; RLS still applies (it is NOT the superadmin).
resource "google_sql_user" "runtime" {
  name     = local.runtime_db_user
  instance = google_sql_database_instance.main.name
  type     = "CLOUD_IAM_SERVICE_ACCOUNT"
}

# ------------------------------------------ app_superadmin BUILT_IN user (D-05a/Path B)
# The cross-tenant superadmin DB role. Its name is the EXACT literal `app_superadmin`
# so it satisfies 0003's `current_user = 'app_superadmin'` bypass predicate verbatim
# (T-04-20 — no rename, no migration). Unlike the runtime SA user above this is a
# BUILT_IN (password) user, NOT a CLOUD_IAM_SERVICE_ACCOUNT, because the bypass
# predicate matches a fixed role name an IAM SA user cannot carry, and because the
# superadmin path authenticates with a stored password (Path B), not IAM ephemeral
# certs. The password is GENERATED (never a committed literal) and flows only
# random_password -> secret_version -> Secret Manager (T-04-16).
resource "random_password" "app_superadmin" {
  length = 32
  # Cloud SQL BUILT_IN passwords accept punctuation; keep a conservative special set
  # so the password is valid in a pg8000 password= field and a Secret Manager payload.
  special          = true
  override_special = "!#%*-_=+:?"
}

resource "google_sql_user" "app_superadmin" {
  name     = "app_superadmin" # EXACT literal — 0003's current_user predicate (T-04-20)
  instance = google_sql_database_instance.main.name
  type     = "BUILT_IN"
  password = random_password.app_superadmin.result
}

# ----------------------------------------- Secret Manager: app_superadmin password (D-05a)
# The SINGLE deliberate stored DB credential (the header invariant's one exception).
# The secret holds ONLY the generated password; the password value never appears in
# any Cloud Run env or IaC literal — only this secret payload (T-04-16). Requires the
# Secret Manager API (secretmanager.googleapis.com) enabled — see infra/README.md.
resource "google_secret_manager_secret" "app_superadmin_db_password" {
  secret_id = var.superadmin_db_secret_id

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "app_superadmin_db_password" {
  secret      = google_secret_manager_secret.app_superadmin_db_password.id
  secret_data = random_password.app_superadmin.result
}

# Resource-scoped secretAccessor (T-04-17 — least privilege): the runtime SA may read
# ONLY this one secret, NOT a project-wide secretAccessor grant. base.py fetches the
# password at runtime via this grant.
resource "google_secret_manager_secret_iam_member" "runtime_superadmin_secret_accessor" {
  secret_id = google_secret_manager_secret.app_superadmin_db_password.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}

# ------------------------------------------- Secret Manager: AI provider keys (D-07 / Phase 7)
# ANTHROPIC_API_KEY (LLM) + OPENAI_API_KEY (embeddings + Whisper). Mirrors the
# app_superadmin password block (:122-142): a secret resource + a resource-scoped
# secretAccessor grant to the runtime SA. The KEY VALUE is NOT committed here — by
# default the secret VERSION is seeded out-of-band per infra/DEPLOY-RUNBOOK.md
# (the var defaults to "" => the *_version resource has count 0). Unlike the
# superadmin password (read at runtime by base.py), these keys are injected
# NATIVELY into the Cloud Run container env via value_source.secret_key_ref below
# — no runtime access_secret_version call (RESEARCH "Don't Hand-Roll": API keys
# have no import-cycle reason to runtime-fetch). secretAccessor is required because
# native secret_key_ref injection still resolves the version with the runtime SA's
# identity at deploy/boot time. The keys are read at call time by the AI seam and
# are NEVER logged / echoed (T-7-05).
resource "google_secret_manager_secret" "anthropic_api_key" {
  secret_id = var.anthropic_api_key_secret_id

  replication {
    auto {}
  }
}

# Optional seed of the ANTHROPIC_API_KEY value. Default var => "" => count 0, i.e.
# NO Terraform-managed version: the real key is added manually with
# `gcloud secrets versions add` per the runbook (the drift-honest default — the
# key never enters committed state, T-7-05). secret_key_ref below uses
# version = "latest" so it binds whichever version exists, manual or seeded.
resource "google_secret_manager_secret_version" "anthropic_api_key" {
  count       = var.anthropic_api_key == "" ? 0 : 1
  secret      = google_secret_manager_secret.anthropic_api_key.id
  secret_data = var.anthropic_api_key
}

resource "google_secret_manager_secret_iam_member" "runtime_anthropic_secret_accessor" {
  secret_id = google_secret_manager_secret.anthropic_api_key.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}

resource "google_secret_manager_secret" "openai_api_key" {
  secret_id = var.openai_api_key_secret_id

  replication {
    auto {}
  }
}

# Optional seed of the OPENAI_API_KEY value — same drift-honest semantics as the
# anthropic_api_key version above (default "" => count 0 => seed manually per runbook).
resource "google_secret_manager_secret_version" "openai_api_key" {
  count       = var.openai_api_key == "" ? 0 : 1
  secret      = google_secret_manager_secret.openai_api_key.id
  secret_data = var.openai_api_key
}

resource "google_secret_manager_secret_iam_member" "runtime_openai_secret_accessor" {
  secret_id = google_secret_manager_secret.openai_api_key.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}

# --------------------------------------------------------- Artifact Registry (D-01)
resource "google_artifact_registry_repository" "backend" {
  location      = var.region
  repository_id = var.repo
  format        = "DOCKER"
  description   = "Nestor Intake backend container images."
}

# ------------------------------------------------------- Runtime service account
resource "google_service_account" "runtime" {
  account_id   = var.runtime_sa_id
  display_name = "Nestor Intake Cloud Run runtime SA"
}

# Least-privilege GCP IAM (V14, T-02-10): EXACTLY the two cloudsql roles the
# connector + IAM login need -- nothing else. No owner/editor/cloudsql.admin.
resource "google_project_iam_member" "runtime_cloudsql_client" {
  project = var.project
  role    = "roles/cloudsql.client" # connect through the connector
  member  = "serviceAccount:${google_service_account.runtime.email}"
}

resource "google_project_iam_member" "runtime_cloudsql_instance_user" {
  project = var.project
  role    = "roles/cloudsql.instanceUser" # IAM DB login
  member  = "serviceAccount:${google_service_account.runtime.email}"
}

# Identity Platform admin (Phase 3, Pitfall 6): EXACTLY the role the login-sync
# claim writes + the superadmin-seed user create/lookup need -- set custom claims,
# create/lookup IdP users. Token VERIFICATION (verify_id_token) needs NO role; only
# claim WRITES / user creation do. Still least-privilege: no firebase.admin /
# owner / editor -- just identitytoolkit.admin (T-03-14).
resource "google_project_iam_member" "runtime_identitytoolkit_admin" {
  project = var.project
  role    = "roles/identitytoolkit.admin"
  member  = "serviceAccount:${google_service_account.runtime.email}"
}

# ------------------------------------------------------ GCS uploads bucket (INFRA-03 / Phase 9)
# The private object store that replaces the legacy Supabase `nestor-uploads` bucket
# (D-12/D-07a). Hardened by construction:
#   - uniform_bucket_level_access = true  -> no per-object ACLs; IAM is the ONLY
#     access-control surface (removes the ACL foot-gun class entirely).
#   - public_access_prevention = "enforced" -> zero public objects, ever; a stray
#     allUsers/allAuthenticatedUsers grant cannot make an object world-readable
#     (D-07a — mitigates T-09-14 information disclosure).
#   - NO versioning block and NO lifecycle rules (D-12): objects are server-authored,
#     space-scoped keys; retention/versioning is out of scope for this phase.
#   - force_destroy = false: a `terraform destroy` cannot silently wipe tenant
#     uploads while objects still exist.
#
# IaC-DRIFT: Terraform state was never adopted for this project (see the Phase 5/7/8
# drift notes in DEPLOY-RUNBOOK.md and .planning/STATE.md). This resource — and the
# two IAM bindings + the STORAGE_BUCKET env below — are the INTENDED end-state only;
# they are INERT until applied out-of-band via the Phase-9 gcloud steps in
# infra/DEPLOY-RUNBOOK.md (D-11). Reconcile via `terraform import` (or keep manual)
# BEFORE the Phase 12 cutover.
resource "google_storage_bucket" "uploads" {
  name     = "${var.project}-nestor-uploads"
  location = var.region

  uniform_bucket_level_access = true       # IAM-only access control (no per-object ACLs)
  public_access_prevention    = "enforced" # zero public objects (D-07a / T-09-14)

  # WR-02: two frontend paths (FinalReportBlock's blob download, ResearchResultsPanel's
  # getArtifactText for PDF generation) `fetch()` the signed GCS URL directly from the app
  # origin. A cross-origin fetch to storage.googleapis.com is browser-blocked unless the
  # bucket echoes the origin — so mirror the Cloud Run CORS allowlist here. Read-only:
  # method GET only (uploads/deletes go THROUGH the backend, never browser->bucket). The
  # dynamic block emits NOTHING when cors_allowed_origins is empty (no broadening default).
  dynamic "cors" {
    for_each = length(var.cors_allowed_origins) > 0 ? [1] : []
    content {
      origin          = var.cors_allowed_origins
      method          = ["GET"]
      response_header = ["Content-Disposition", "Content-Type"]
      max_age_seconds = 3600
    }
  }

  # Deliberately NO versioning block and NO lifecycle_rule blocks (D-12): out of scope.
  force_destroy = false # never auto-wipe tenant uploads on destroy
}

# Bucket-scoped storage.objectAdmin for the runtime SA (least privilege, T-09-15).
# Scoped to THIS bucket only — NOT a project-wide roles/storage.* grant — so the SA
# can read/write/delete objects in the uploads bucket and nothing else. objectAdmin
# (not objectViewer/objectCreator) is required because the backend both writes
# uploads and deletes objects on cleanup (D-09).
resource "google_storage_bucket_iam_member" "runtime_object_admin" {
  bucket = google_storage_bucket.uploads.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${google_service_account.runtime.email}"
}

# Keyless signBlob grant (criterion 1 / T-09-13): the runtime SA impersonates ITSELF
# to mint V4 signed download URLs via the IAM signBlob API — NO service-account JSON
# key exists anywhere (app/storage/gcs.py signs with ADC + service_account_email +
# access_token; the CI guard scripts/ci_no_sa_json_key.sh bans any SA-JSON-key path).
# This serviceAccountTokenCreator self-binding is a SEPARATE grant from the object
# access above (Pitfall 2): storage.objectAdmin lets the SA read/write objects, but
# signing a URL requires the DISTINCT iam.serviceAccountTokenCreator role on the SA
# principal itself. Without this binding, signed_download_url() 403s at signBlob even
# though object access works.
resource "google_service_account_iam_member" "runtime_token_creator_self" {
  service_account_id = google_service_account.runtime.name
  role               = "roles/iam.serviceAccountTokenCreator"
  member             = "serviceAccount:${google_service_account.runtime.email}"
}

# -------------------------------------------------- Cloud Run SERVICE (D-04/INFRA-04)
# gen2 (the v2 resource default), runtime SA, max-instances=4 (D-04 connection
# math). Env carries ONLY non-secret connector config -- no stored credential,
# no DSN (D-09). The container listens on the Cloud-Run-injected $PORT.
resource "google_cloud_run_v2_service" "api" {
  name     = var.service_name
  location = var.region

  template {
    service_account = google_service_account.runtime.email

    # D-07: raise the Cloud Run request timeout to 900s so a long-lived
    # `text/event-stream` (SSE) skill-run-progress connection is not severed at
    # the 300s Cloud Run default (streams would otherwise reliably die at ~5 min).
    # Paired with the app's 10-min in-handler MAX_STREAM_SECONDS cap (plan 08-01)
    # so a hung run can never hold a connection for the full 900s window.
    # IaC-DRIFT: Terraform state was never adopted; this edit is inert until the
    # out-of-band `gcloud run services update ... --timeout=900` in DEPLOY-RUNBOOK.md.
    timeout = "900s"

    # D-01a: scale to ZERO when idle (min_instance_count = 0 — warm-pool knob OFF,
    # no idle cost) while max stays capped so worst-case pooled connections stay
    # under the Cloud SQL tier (D-04 math: 4 * (pool 2 + overflow 3) = 20 << 100).
    # CPU-always-allocated (resources.cpu_idle = false below) lets a request's
    # background work — the 90–120s LLM/Whisper calls (AI-06) — finish after the
    # response without CPU throttling, even though there is no warm pool.
    scaling {
      min_instance_count = 0 # scale to zero; warm-pool OFF (D-01a)
      max_instance_count = 4 # D-04 connection-math ceiling (T-7-15)
    }

    containers {
      image = local.image

      # Cloud Run injects PORT (default 8080); the Dockerfile binds $PORT.
      ports {
        container_port = 8080
      }

      # D-01a: CPU ALWAYS-ALLOCATED. In the Cloud Run v2 API this is the
      # `resources.cpu_idle = false` field — the native equivalent of the gen1
      # `run.googleapis.com/cpu-throttling = "false"` annotation. CPU is NOT
      # throttled between requests, so background tasks spawned by a handler (the
      # long LLM/embedding/Whisper calls) reliably run to completion even with
      # min-instances=0 (no warm pool). Paired with AI-06 (no DB connection held
      # across those calls) this is the "reliable background work, scale to zero"
      # configuration the phase requires.
      resources {
        cpu_idle = false
      }

      # Non-secret connector config only (D-09). The mode-switched engine factory
      # selects the connector branch because INSTANCE_CONNECTION_NAME is set.
      env {
        name  = "INSTANCE_CONNECTION_NAME"
        value = google_sql_database_instance.main.connection_name
      }
      env {
        name  = "DB_USER"
        value = local.runtime_db_user
      }
      env {
        name  = "DB_NAME"
        value = google_sql_database.app.name
      }
      # INFRA-03 (Phase 9): the GCS uploads bucket name (non-secret config, D-09).
      # app.storage.gcs reads STORAGE_BUCKET at call time (get_settings().storage_bucket)
      # to resolve the target bucket for upload/signed-URL/delete. Mirrors the
      # INSTANCE_CONNECTION_NAME env above — a plain non-secret value, no Secret
      # Manager reference. IaC-DRIFT: inert until the runbook `--update-env-vars
      # STORAGE_BUCKET=...` (Step 9.4) sets it on the live service.
      env {
        name  = "STORAGE_BUCKET"
        value = google_storage_bucket.uploads.name
      }
      # Path B (D-05a): the secret RESOURCE NAME (NOT the password value) that
      # base.py::_load_superadmin_password() reads at runtime via Secret Manager.
      # `<secret resource name>/versions/latest` is the exact form
      # client.access_secret_version(name=...) expects. The password value never
      # appears here -- only the pointer to it (T-04-16).
      env {
        name  = "SUPERADMIN_DB_PASSWORD_SECRET"
        value = "${google_secret_manager_secret.app_superadmin_db_password.name}/versions/latest"
      }
      # Deliberately NO DSN env and NO stored DB credential VALUE here (D-09/V10);
      # SUPERADMIN_DB_PASSWORD_SECRET above carries only the secret name, not the password.

      # D-07: AI provider keys injected NATIVELY from Secret Manager via
      # value_source.secret_key_ref (NOT a runtime access_secret_version call).
      # Cloud Run resolves `version = "latest"` with the runtime SA's identity at
      # deploy/boot — hence the resource-scoped secretAccessor grants above. The
      # KEY VALUE never appears in this config or in Terraform state; only the
      # secret reference does. The AI seam reads ANTHROPIC_API_KEY / OPENAI_API_KEY
      # from the process env at call time and must NEVER log them (T-7-05).
      env {
        name = "ANTHROPIC_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.anthropic_api_key.secret_id
            version = "latest"
          }
        }
      }
      env {
        name = "OPENAI_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.openai_api_key.secret_id
            version = "latest"
          }
        }
      }
    }
  }

  depends_on = [
    google_project_iam_member.runtime_cloudsql_client,
    google_project_iam_member.runtime_cloudsql_instance_user,
    # Path B: the secret, its version, and the runtime SA's scoped read grant must
    # exist before the service boots, or the first superadmin request 500s when
    # base.py tries to read the (not-yet-readable) secret.
    google_secret_manager_secret_version.app_superadmin_db_password,
    google_secret_manager_secret_iam_member.runtime_superadmin_secret_accessor,
    # D-07: the AI-key secrets + the runtime SA's scoped read grants must exist
    # before the service boots, or native secret_key_ref injection fails to
    # resolve `latest` at deploy time. (The secret VERSIONS are seeded out-of-band
    # per the runbook by default, so they are intentionally NOT in this edge.)
    google_secret_manager_secret_iam_member.runtime_anthropic_secret_accessor,
    google_secret_manager_secret_iam_member.runtime_openai_secret_accessor,
    # INFRA-03 (Phase 9): the bucket + its bucket-scoped objectAdmin grant + the
    # keyless-signBlob self-binding must exist before the service boots, or the
    # first storage request (upload/signed-URL/delete) fails — objectAdmin 403 on
    # object access, or signBlob 403 on URL signing (Pitfall 2). The STORAGE_BUCKET
    # env already creates an implicit edge to the bucket; the two IAM bindings do
    # not, so declare them explicitly.
    google_storage_bucket_iam_member.runtime_object_admin,
    google_service_account_iam_member.runtime_token_creator_self,
  ]
}

# ----------------------------------------------------- Cloud Run migration JOB (D-05)
# Same image + same runtime SA as the service; overrides the Uvicorn CMD with
# `alembic upgrade head` (RESEARCH Pattern 3 / verified HCL). It also sets
# RUNTIME_DB_USER so the 0005 migration grants the correct IAM DB role.
resource "google_cloud_run_v2_job" "migrate" {
  name     = "nestor-migrate"
  location = var.region

  template {
    template {
      service_account = google_service_account.runtime.email

      containers {
        image = local.image
        args  = ["alembic", "upgrade", "head"]

        env {
          name  = "INSTANCE_CONNECTION_NAME"
          value = google_sql_database_instance.main.connection_name
        }
        env {
          name  = "DB_USER"
          value = local.runtime_db_user
        }
        env {
          name  = "DB_NAME"
          value = google_sql_database.app.name
        }
        # The 0005 GRANT reads this to grant the space-scoped privileges to the
        # runtime SA IAM DB user (OQ1/A5). Same value as DB_USER.
        env {
          name  = "RUNTIME_DB_USER"
          value = local.runtime_db_user
        }
      }
    }
  }

  depends_on = [
    google_project_iam_member.runtime_cloudsql_client,
    google_project_iam_member.runtime_cloudsql_instance_user,
    google_sql_user.runtime,
    # WR-04: the Job's execution (alembic upgrade head -> 0005 GRANT) runs against
    # DB_NAME, so the application database must exist before the Job is created.
    # The env references above do not create an implicit edge to the database, so
    # declare it explicitly to keep the create-ordering graph complete.
    google_sql_database.app,
  ]
}

# ------------------------------------------------ Cloud Run superadmin-seed JOB (D-05)
# One-shot first-superadmin bootstrap (Open Q3 / D-05). Same image + same runtime SA
# as the service; overrides the Uvicorn CMD with `python -m scripts.seed_superadmin`
# (mirrors the migration Job's alt-entrypoint pattern). The runtime SA carries
# roles/identitytoolkit.admin (above), so the claim write + IdP user create/lookup
# succeed via ADC -- NO JSON SA key (T-03-15). The SUPERADMIN_PASSWORD is NOT set here
# (never stored in IaC/state); it is supplied at execution time with
# `gcloud run jobs execute ... --update-env-vars SUPERADMIN_PASSWORD=...` (see README).
resource "google_cloud_run_v2_job" "seed_superadmin" {
  name     = "nestor-seed-superadmin"
  location = var.region

  template {
    template {
      service_account = google_service_account.runtime.email

      containers {
        image = local.image
        args  = ["python", "-m", "scripts.seed_superadmin"]

        env {
          name  = "INSTANCE_CONNECTION_NAME"
          value = google_sql_database_instance.main.connection_name
        }
        env {
          name  = "DB_USER"
          value = local.runtime_db_user
        }
        env {
          name  = "DB_NAME"
          value = google_sql_database.app.name
        }
        # The first superadmin's email. The PASSWORD is intentionally absent here and
        # supplied at execute time (T-03-15). GOOGLE_CLOUD_PROJECT is injected by Cloud
        # Run, so the Admin SDK's ADC init resolves the Identity Platform project.
        env {
          name  = "SUPERADMIN_EMAIL"
          value = var.superadmin_email
        }
      }
    }
  }

  depends_on = [
    google_project_iam_member.runtime_cloudsql_client,
    google_project_iam_member.runtime_cloudsql_instance_user,
    google_project_iam_member.runtime_identitytoolkit_admin,
    google_sql_user.runtime,
    # The seed writes the membership row -> the database (and the migrated schema) must
    # exist first; the migration Job must have run before this is executed.
    google_sql_database.app,
  ]
}

# ------------------------------------------------------------- Invoker policy (OQ2)
# Authenticated-only by default (allow_unauthenticated=false): the deployed
# /readyz is reached via `gcloud run services proxy` (T-02-13). Public health-only
# is an explicit opt-in -- this binding is created ONLY when the var is true.
resource "google_cloud_run_v2_service_iam_member" "invoker" {
  count    = var.allow_unauthenticated ? 1 : 0
  name     = google_cloud_run_v2_service.api.name
  location = google_cloud_run_v2_service.api.location
  role     = "roles/run.invoker"
  member   = "allUsers"
}
