# Nestor Intake GCP footprint (D-01, RESEARCH Pattern 4).
#
# Provisions, with IAM database authentication and NO stored DB credential
# anywhere (D-03/D-09/V10):
#   - a POSTGRES_16 Cloud SQL instance (IAM auth on, public IP, NO IP allowlist)
#   - the application database + the runtime SA's IAM DB user (login only)
#   - an Artifact Registry Docker repo for the backend image
#   - the least-privilege Cloud Run runtime service account (V14)
#   - the Cloud Run gen2 service (max-instances=4, D-04) + the alembic migration Job
#
# The Cloud SQL Python Connector tunnels via the Cloud SQL Admin API over TLS
# with ephemeral certs (D-03) -- so there is NO IP allowlist and the Cloud Run
# resources need NO Cloud-SQL-instance attachment flag / annotation (the
# RESEARCH anti-pattern). The only credentialed path to the DB is the runtime
# SA's IAM identity (API-01/D-09).
#
# Phase 4 (D-05a / Path B) — the SINGLE deliberate exception to the
# "NO stored DB credential anywhere" invariant above: the cross-tenant superadmin
# code path needs a DB role that satisfies 0003's `current_user = 'app_superadmin'`
# bypass predicate. Cloud SQL forbids BYPASSRLS and an IAM SA user cannot be named
# the bare literal `app_superadmin`, so this phase provisions a BUILT_IN Cloud SQL
# user named the EXACT literal `app_superadmin` whose password is generated by
# `random_password` (never a committed literal), stored ONLY in Secret Manager,
# and read at runtime by base.py::_load_superadmin_password() via a resource-scoped
# `secretAccessor` grant on that one secret. The Cloud Run env carries only the
# secret RESOURCE NAME (SUPERADMIN_DB_PASSWORD_SECRET) -- never the password value
# -- so the password never lands in IaC/state/env plaintext (T-04-16/T-04-17).

locals {
  # The IAM DB username = the runtime SA email WITHOUT the ".gserviceaccount.com"
  # suffix (Cloud SQL IAM-login convention). Used for the google_sql_user name,
  # the service DB_USER env, and the Job's DB_USER / RUNTIME_DB_USER env.
  runtime_db_user = trimsuffix(google_service_account.runtime.email, ".gserviceaccount.com")

  image = "${var.region}-docker.pkg.dev/${var.project}/${var.repo}/backend:${var.image_tag}"

  # Phase 12 (INFRA-05 / D-07): the frontend image lives in the SAME `nestor`
  # Artifact Registry repo as the backend (path `.../nestor/frontend:<tag>`); no new
  # repo is provisioned. Mirrors `local.image` above, pathed to the frontend image
  # and driven by its own `var.frontend_image_tag` (passed on apply, two-step deploy).
  frontend_image = "${var.region}-docker.pkg.dev/${var.project}/${var.repo}/frontend:${var.frontend_image_tag}"
}

# --------------------------------------------------------------- Cloud SQL (D-01/D-03)
# POSTGRES_16, IAM auth ON, public IP, NO authorized-networks allowlist (the
# connector tunnels via the Admin API, not an IP list -- T-02-14). deletion
# protection ON so a stray destroy cannot drop the tenant DB.
resource "google_sql_database_instance" "main" {
  name             = var.instance_name
  region           = var.region
  database_version = "POSTGRES_16"

  deletion_protection = true

  settings {
    tier = var.tier # db-custom-1-3840 -> default max_connections=100 (A4/D-04)

    # IAM database authentication -- the ONLY auth path; there is no built-in
    # DB credential to store or leak (D-03/D-09).
    database_flags {
      name  = "cloudsql.iam_authentication"
      value = "on"
    }

    ip_configuration {
      ipv4_enabled = true # public IP; the connector secures the channel (D-03).
      # Intentionally NO IP allowlist block here -- access is gated by IAM, not
      # by network range (T-02-14). Adding one is the anti-pattern we avoid.
    }
  }
}

# The application database (D-01).
resource "google_sql_database" "app" {
  name     = var.db_name
  instance = google_sql_database_instance.main.name

  # WR-06: the instance-level deletion_protection does NOT cover the database
  # object. Protect the tenant DB itself so a `terraform destroy` targeting this
  # resource (or a config change forcing its replacement) cannot silently drop the
  # `nestor` database while the instance survives. deletion_protection guards the
  # provider-level destroy; prevent_destroy is the Terraform-core backstop.
  deletion_protection = true

  lifecycle {
    prevent_destroy = true
  }
}

# The runtime SA's IAM DB user. type=CLOUD_IAM_SERVICE_ACCOUNT grants LOGIN ONLY
# -- zero Postgres privileges by default (Pitfall 3). The 0005 migration GRANTs
# it the space-scoped privilege set; RLS still applies (it is NOT the superadmin).
resource "google_sql_user" "runtime" {
  name     = local.runtime_db_user
  instance = google_sql_database_instance.main.name
  type     = "CLOUD_IAM_SERVICE_ACCOUNT"
}

# ------------------------------------------ app_superadmin BUILT_IN user (D-05a/Path B)
# The cross-tenant superadmin DB role. Its name is the EXACT literal `app_superadmin`
# so it satisfies 0003's `current_user = 'app_superadmin'` bypass predicate verbatim
# (T-04-20 — no rename, no migration). Unlike the runtime SA user above this is a
# BUILT_IN (password) user, NOT a CLOUD_IAM_SERVICE_ACCOUNT, because the bypass
# predicate matches a fixed role name an IAM SA user cannot carry, and because the
# superadmin path authenticates with a stored password (Path B), not IAM ephemeral
# certs. The password is GENERATED (never a committed literal) and flows only
# random_password -> secret_version -> Secret Manager (T-04-16).
resource "random_password" "app_superadmin" {
  length = 32
  # Cloud SQL BUILT_IN passwords accept punctuation; keep a conservative special set
  # so the password is valid in a pg8000 password= field and a Secret Manager payload.
  special          = true
  override_special = "!#%*-_=+:?"
}

resource "google_sql_user" "app_superadmin" {
  name     = "app_superadmin" # EXACT literal — 0003's current_user predicate (T-04-20)
  instance = google_sql_database_instance.main.name
  type     = "BUILT_IN"
  password = random_password.app_superadmin.result
}

# ----------------------------------------- Secret Manager: app_superadmin password (D-05a)
# The SINGLE deliberate stored DB credential (the header invariant's one exception).
# The secret holds ONLY the generated password; the password value never appears in
# any Cloud Run env or IaC literal — only this secret payload (T-04-16). Requires the
# Secret Manager API (secretmanager.googleapis.com) enabled — see infra/README.md.
resource "google_secret_manager_secret" "app_superadmin_db_password" {
  secret_id = var.superadmin_db_secret_id

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "app_superadmin_db_password" {
  secret      = google_secret_manager_secret.app_superadmin_db_password.id
  secret_data = random_password.app_superadmin.result
}

# Resource-scoped secretAccessor (T-04-17 — least privilege): the runtime SA may read
# ONLY this one secret, NOT a project-wide secretAccessor grant. base.py fetches the
# password at runtime via this grant.
resource "google_secret_manager_secret_iam_member" "runtime_superadmin_secret_accessor" {
  secret_id = google_secret_manager_secret.app_superadmin_db_password.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}

# ------------------------------------------- Secret Manager: AI provider keys (D-07 / Phase 7)
# ANTHROPIC_API_KEY (LLM) + OPENAI_API_KEY (embeddings + Whisper). Mirrors the
# app_superadmin password block (:122-142): a secret resource + a resource-scoped
# secretAccessor grant to the runtime SA. The KEY VALUE is NOT committed here — by
# default the secret VERSION is seeded out-of-band per infra/DEPLOY-RUNBOOK.md
# (the var defaults to "" => the *_version resource has count 0). Unlike the
# superadmin password (read at runtime by base.py), these keys are injected
# NATIVELY into the Cloud Run container env via value_source.secret_key_ref below
# — no runtime access_secret_version call (RESEARCH "Don't Hand-Roll": API keys
# have no import-cycle reason to runtime-fetch). secretAccessor is required because
# native secret_key_ref injection still resolves the version with the runtime SA's
# identity at deploy/boot time. The keys are read at call time by the AI seam and
# are NEVER logged / echoed (T-7-05).
resource "google_secret_manager_secret" "anthropic_api_key" {
  secret_id = var.anthropic_api_key_secret_id

  replication {
    auto {}
  }
}

# Optional seed of the ANTHROPIC_API_KEY value. Default var => "" => count 0, i.e.
# NO Terraform-managed version: the real key is added manually with
# `gcloud secrets versions add` per the runbook (the drift-honest default — the
# key never enters committed state, T-7-05). secret_key_ref below uses
# version = "latest" so it binds whichever version exists, manual or seeded.
resource "google_secret_manager_secret_version" "anthropic_api_key" {
  count       = var.anthropic_api_key == "" ? 0 : 1
  secret      = google_secret_manager_secret.anthropic_api_key.id
  secret_data = var.anthropic_api_key
}

resource "google_secret_manager_secret_iam_member" "runtime_anthropic_secret_accessor" {
  secret_id = google_secret_manager_secret.anthropic_api_key.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}

resource "google_secret_manager_secret" "openai_api_key" {
  secret_id = var.openai_api_key_secret_id

  replication {
    auto {}
  }
}

# Optional seed of the OPENAI_API_KEY value — same drift-honest semantics as the
# anthropic_api_key version above (default "" => count 0 => seed manually per runbook).
resource "google_secret_manager_secret_version" "openai_api_key" {
  count       = var.openai_api_key == "" ? 0 : 1
  secret      = google_secret_manager_secret.openai_api_key.id
  secret_data = var.openai_api_key
}

resource "google_secret_manager_secret_iam_member" "runtime_openai_secret_accessor" {
  secret_id = google_secret_manager_secret.openai_api_key.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}

# ------------------------------------------------ Resend transactional email (D-13 / Phase 10)
# The RESEND_API_KEY credential — the ONLY new secret this phase adds. Structurally a
# verbatim copy of the anthropic_api_key trio above: the secret RESOURCE + a
# resource-scoped secretAccessor grant to the runtime SA are declared in IaC, and the
# VALUE is seeded out-of-band per the runbook (drift-honest default => count 0 => NO
# Terraform-managed version, so the key never enters committed state, T-10-04). The
# Cloud Run env below injects it natively via value_source.secret_key_ref (version
# "latest"); the mail module reads RESEND_API_KEY from the process env at call time and
# must NEVER log it.
resource "google_secret_manager_secret" "resend_api_key" {
  secret_id = var.resend_api_key_secret_id

  replication {
    auto {}
  }
}

# Optional seed of the RESEND_API_KEY value — same drift-honest semantics as the
# anthropic_api_key version above (default "" => count 0 => seed manually per the runbook,
# T-10-04). secret_key_ref below uses version = "latest" so it binds whichever version
# exists, manual or seeded.
resource "google_secret_manager_secret_version" "resend_api_key" {
  count       = var.resend_api_key == "" ? 0 : 1
  secret      = google_secret_manager_secret.resend_api_key.id
  secret_data = var.resend_api_key
}

resource "google_secret_manager_secret_iam_member" "runtime_resend_secret_accessor" {
  secret_id = google_secret_manager_secret.resend_api_key.secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.runtime.email}"
}

# --------------------------------------------------------- Artifact Registry (D-01)
resource "google_artifact_registry_repository" "backend" {
  location      = var.region
  repository_id = var.repo
  format        = "DOCKER"
  description   = "Nestor Intake backend container images."
}

# ------------------------------------------------------- Runtime service account
resource "google_service_account" "runtime" {
  account_id   = var.runtime_sa_id
  display_name = "Nestor Intake Cloud Run runtime SA"
}

# Least-privilege GCP IAM (V14, T-02-10): EXACTLY the two cloudsql roles the
# connector + IAM login need -- nothing else. No owner/editor/cloudsql.admin.
resource "google_project_iam_member" "runtime_cloudsql_client" {
  project = var.project
  role    = "roles/cloudsql.client" # connect through the connector
  member  = "serviceAccount:${google_service_account.runtime.email}"
}

resource "google_project_iam_member" "runtime_cloudsql_instance_user" {
  project = var.project
  role    = "roles/cloudsql.instanceUser" # IAM DB login
  member  = "serviceAccount:${google_service_account.runtime.email}"
}

# Identity Platform admin (Phase 3, Pitfall 6): EXACTLY the role the login-sync
# claim writes + the superadmin-seed user create/lookup need -- set custom claims,
# create/lookup IdP users. Token VERIFICATION (verify_id_token) needs NO role; only
# claim WRITES / user creation do. Still least-privilege: no firebase.admin /
# owner / editor -- just identitytoolkit.admin (T-03-14).
resource "google_project_iam_member" "runtime_identitytoolkit_admin" {
  project = var.project
  role    = "roles/identitytoolkit.admin"
  member  = "serviceAccount:${google_service_account.runtime.email}"
}

# ------------------------------------------------------ GCS uploads bucket (INFRA-03 / Phase 9)
# The private object store that replaces the legacy Supabase `nestor-uploads` bucket
# (D-12/D-07a). Hardened by construction:
#   - uniform_bucket_level_access = true  -> no per-object ACLs; IAM is the ONLY
#     access-control surface (removes the ACL foot-gun class entirely).
#   - public_access_prevention = "enforced" -> zero public objects, ever; a stray
#     allUsers/allAuthenticatedUsers grant cannot make an object world-readable
#     (D-07a — mitigates T-09-14 information disclosure).
#   - NO versioning block and NO lifecycle rules (D-12): objects are server-authored,
#     space-scoped keys; retention/versioning is out of scope for this phase.
#   - force_destroy = false: a `terraform destroy` cannot silently wipe tenant
#     uploads while objects still exist.
#
# IaC-DRIFT: Terraform state was never adopted for this project (see the Phase 5/7/8
# drift notes in DEPLOY-RUNBOOK.md and .planning/STATE.md). This resource — and the
# two IAM bindings + the STORAGE_BUCKET env below — are the INTENDED end-state only;
# they are INERT until applied out-of-band via the Phase-9 gcloud steps in
# infra/DEPLOY-RUNBOOK.md (D-11). Reconcile via `terraform import` (or keep manual)
# BEFORE the Phase 12 cutover.
resource "google_storage_bucket" "uploads" {
  name     = "${var.project}-nestor-uploads"
  location = var.region

  uniform_bucket_level_access = true       # IAM-only access control (no per-object ACLs)
  public_access_prevention    = "enforced" # zero public objects (D-07a / T-09-14)

  # WR-02: two frontend paths (FinalReportBlock's blob download, ResearchResultsPanel's
  # getArtifactText for PDF generation) `fetch()` the signed GCS URL directly from the app
  # origin. A cross-origin fetch to storage.googleapis.com is browser-blocked unless the
  # bucket echoes the origin — so mirror the Cloud Run CORS allowlist here. Read-only:
  # method GET only (uploads/deletes go THROUGH the backend, never browser->bucket). The
  # dynamic block emits NOTHING when cors_allowed_origins is empty (no broadening default).
  dynamic "cors" {
    for_each = length(var.cors_allowed_origins) > 0 ? [1] : []
    content {
      origin          = var.cors_allowed_origins
      method          = ["GET"]
      response_header = ["Content-Disposition", "Content-Type"]
      max_age_seconds = 3600
    }
  }

  # Deliberately NO versioning block and NO lifecycle_rule blocks (D-12): out of scope.
  force_destroy = false # never auto-wipe tenant uploads on destroy
}

# Bucket-scoped storage.objectAdmin for the runtime SA (least privilege, T-09-15).
# Scoped to THIS bucket only — NOT a project-wide roles/storage.* grant — so the SA
# can read/write/delete objects in the uploads bucket and nothing else. objectAdmin
# (not objectViewer/objectCreator) is required because the backend both writes
# uploads and deletes objects on cleanup (D-09).
resource "google_storage_bucket_iam_member" "runtime_object_admin" {
  bucket = google_storage_bucket.uploads.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${google_service_account.runtime.email}"
}

# Keyless signBlob grant (criterion 1 / T-09-13): the runtime SA impersonates ITSELF
# to mint V4 signed download URLs via the IAM signBlob API — NO service-account JSON
# key exists anywhere (app/storage/gcs.py signs with ADC + service_account_email +
# access_token; the CI guard scripts/ci_no_sa_json_key.sh bans any SA-JSON-key path).
# This serviceAccountTokenCreator self-binding is a SEPARATE grant from the object
# access above (Pitfall 2): storage.objectAdmin lets the SA read/write objects, but
# signing a URL requires the DISTINCT iam.serviceAccountTokenCreator role on the SA
# principal itself. Without this binding, signed_download_url() 403s at signBlob even
# though object access works.
resource "google_service_account_iam_member" "runtime_token_creator_self" {
  service_account_id = google_service_account.runtime.name
  role               = "roles/iam.serviceAccountTokenCreator"
  member             = "serviceAccount:${google_service_account.runtime.email}"
}

# -------------------------------------------------- Cloud Run SERVICE (D-04/INFRA-04)
# gen2 (the v2 resource default), runtime SA, max-instances=4 (D-04 connection
# math). Env carries ONLY non-secret connector config -- no stored credential,
# no DSN (D-09). The container listens on the Cloud-Run-injected $PORT.
resource "google_cloud_run_v2_service" "api" {
  name     = var.service_name
  location = var.region

  template {
    service_account = google_service_account.runtime.email

    # D-07: raise the Cloud Run request timeout to 900s so a long-lived
    # `text/event-stream` (SSE) skill-run-progress connection is not severed at
    # the 300s Cloud Run default (streams would otherwise reliably die at ~5 min).
    # Paired with the app's 10-min in-handler MAX_STREAM_SECONDS cap (plan 08-01)
    # so a hung run can never hold a connection for the full 900s window.
    # IaC-DRIFT: Terraform state was never adopted; this edit is inert until the
    # out-of-band `gcloud run services update ... --timeout=900` in DEPLOY-RUNBOOK.md.
    timeout = "900s"

    # D-01a: scale to ZERO when idle (min_instance_count = 0 — warm-pool knob OFF,
    # no idle cost) while max stays capped so worst-case pooled connections stay
    # under the Cloud SQL tier (D-04 math: 4 * (pool 2 + overflow 3) = 20 << 100).
    # CPU-always-allocated (resources.cpu_idle = false below) lets a request's
    # background work — the 90–120s LLM/Whisper calls (AI-06) — finish after the
    # response without CPU throttling, even though there is no warm pool.
    scaling {
      min_instance_count = 0 # scale to zero; warm-pool OFF (D-01a)
      max_instance_count = 4 # D-04 connection-math ceiling (T-7-15)
    }

    containers {
      image = local.image

      # Cloud Run injects PORT (default 8080); the Dockerfile binds $PORT.
      ports {
        container_port = 8080
      }

      # D-01a: CPU ALWAYS-ALLOCATED. In the Cloud Run v2 API this is the
      # `resources.cpu_idle = false` field — the native equivalent of the gen1
      # `run.googleapis.com/cpu-throttling = "false"` annotation. CPU is NOT
      # throttled between requests, so background tasks spawned by a handler (the
      # long LLM/embedding/Whisper calls) reliably run to completion even with
      # min-instances=0 (no warm pool). Paired with AI-06 (no DB connection held
      # across those calls) this is the "reliable background work, scale to zero"
      # configuration the phase requires.
      resources {
        cpu_idle = false
      }

      # Non-secret connector config only (D-09). The mode-switched engine factory
      # selects the connector branch because INSTANCE_CONNECTION_NAME is set.
      env {
        name  = "INSTANCE_CONNECTION_NAME"
        value = google_sql_database_instance.main.connection_name
      }
      env {
        name  = "DB_USER"
        value = local.runtime_db_user
      }
      env {
        name  = "DB_NAME"
        value = google_sql_database.app.name
      }
      # INFRA-03 (Phase 9): the GCS uploads bucket name (non-secret config, D-09).
      # app.storage.gcs reads STORAGE_BUCKET at call time (get_settings().storage_bucket)
      # to resolve the target bucket for upload/signed-URL/delete. Mirrors the
      # INSTANCE_CONNECTION_NAME env above — a plain non-secret value, no Secret
      # Manager reference. IaC-DRIFT: inert until the runbook `--update-env-vars
      # STORAGE_BUCKET=...` (Step 9.4) sets it on the live service.
      env {
        name  = "STORAGE_BUCKET"
        value = google_storage_bucket.uploads.name
      }
      # Phase 10 (D-08 / D-15): two PLAIN non-secret mail-config env vars (mirror the
      # STORAGE_BUCKET pattern above — no Secret Manager reference). NESTOR_ADMIN_EMAIL is
      # the ops recipient of the admin_validated notification; APP_BASE_URL is the origin
      # the mail module uses to build CTA links + the logo asset URL. IaC-DRIFT: inert
      # until the runbook `--update-env-vars NESTOR_ADMIN_EMAIL=...,APP_BASE_URL=...`
      # (Phase-10 step) sets them on the live service.
      env {
        name  = "NESTOR_ADMIN_EMAIL"
        value = var.nestor_admin_email
      }
      env {
        name  = "APP_BASE_URL"
        value = var.app_base_url
      }
      # Phase 14 (SEAM-02 / D-06): the tribunal-api service URL WITHOUT a path — read by
      # app/research/tribunal_client.py as the OIDC audience it mints an ID token for when
      # calling /api/orgs/ensure + /api/projects/ensure (14-02-SUMMARY). PLAIN non-secret
      # (a service URL, never a Secret Manager reference). IaC-DRIFT: inert until the
      # runbook `--update-env-vars TRIBUNAL_SERVICE_URL=<captured describe url>` on nestor-api
      # (§ Phase 14, Step 14.d) sets it live — same captured URL as tribunal-api's own aud.
      env {
        name  = "TRIBUNAL_SERVICE_URL"
        value = var.tribunal_service_url
      }
      # Path B (D-05a): the secret RESOURCE NAME (NOT the password value) that
      # base.py::_load_superadmin_password() reads at runtime via Secret Manager.
      # `<secret resource name>/versions/latest` is the exact form
      # client.access_secret_version(name=...) expects. The password value never
      # appears here -- only the pointer to it (T-04-16).
      env {
        name  = "SUPERADMIN_DB_PASSWORD_SECRET"
        value = "${google_secret_manager_secret.app_superadmin_db_password.name}/versions/latest"
      }
      # Deliberately NO DSN env and NO stored DB credential VALUE here (D-09/V10);
      # SUPERADMIN_DB_PASSWORD_SECRET above carries only the secret name, not the password.

      # D-07: AI provider keys injected NATIVELY from Secret Manager via
      # value_source.secret_key_ref (NOT a runtime access_secret_version call).
      # Cloud Run resolves `version = "latest"` with the runtime SA's identity at
      # deploy/boot — hence the resource-scoped secretAccessor grants above. The
      # KEY VALUE never appears in this config or in Terraform state; only the
      # secret reference does. The AI seam reads ANTHROPIC_API_KEY / OPENAI_API_KEY
      # from the process env at call time and must NEVER log them (T-7-05).
      env {
        name = "ANTHROPIC_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.anthropic_api_key.secret_id
            version = "latest"
          }
        }
      }
      env {
        name = "OPENAI_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.openai_api_key.secret_id
            version = "latest"
          }
        }
      }
      # Phase 10 (D-13): RESEND_API_KEY injected NATIVELY from Secret Manager via
      # value_source.secret_key_ref (mirror the ANTHROPIC/OPENAI keys above). The KEY
      # VALUE never appears in this config or in Terraform state; only the secret
      # reference does. The mail module reads RESEND_API_KEY from the process env at call
      # time and must NEVER log it (T-10-04).
      env {
        name = "RESEND_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.resend_api_key.secret_id
            version = "latest"
          }
        }
      }
    }
  }

  depends_on = [
    google_project_iam_member.runtime_cloudsql_client,
    google_project_iam_member.runtime_cloudsql_instance_user,
    # Path B: the secret, its version, and the runtime SA's scoped read grant must
    # exist before the service boots, or the first superadmin request 500s when
    # base.py tries to read the (not-yet-readable) secret.
    google_secret_manager_secret_version.app_superadmin_db_password,
    google_secret_manager_secret_iam_member.runtime_superadmin_secret_accessor,
    # D-07: the AI-key secrets + the runtime SA's scoped read grants must exist
    # before the service boots, or native secret_key_ref injection fails to
    # resolve `latest` at deploy time. (The secret VERSIONS are seeded out-of-band
    # per the runbook by default, so they are intentionally NOT in this edge.)
    google_secret_manager_secret_iam_member.runtime_anthropic_secret_accessor,
    google_secret_manager_secret_iam_member.runtime_openai_secret_accessor,
    # Phase 10 (D-13): the RESEND_API_KEY secret's runtime SA read grant must exist
    # before the service boots, or native secret_key_ref injection fails to resolve
    # `latest` at deploy time. (The secret VERSION is seeded out-of-band per the runbook
    # by default, so it is intentionally NOT in this edge.)
    google_secret_manager_secret_iam_member.runtime_resend_secret_accessor,
    # INFRA-03 (Phase 9): the bucket + its bucket-scoped objectAdmin grant + the
    # keyless-signBlob self-binding must exist before the service boots, or the
    # first storage request (upload/signed-URL/delete) fails — objectAdmin 403 on
    # object access, or signBlob 403 on URL signing (Pitfall 2). The STORAGE_BUCKET
    # env already creates an implicit edge to the bucket; the two IAM bindings do
    # not, so declare them explicitly.
    google_storage_bucket_iam_member.runtime_object_admin,
    google_service_account_iam_member.runtime_token_creator_self,
  ]
}

# ----------------------------------------------------- Cloud Run migration JOB (D-05)
# Same image + same runtime SA as the service; overrides the Uvicorn CMD with
# `alembic upgrade head` (RESEARCH Pattern 3 / verified HCL). It also sets
# RUNTIME_DB_USER so the 0005 migration grants the correct IAM DB role.
resource "google_cloud_run_v2_job" "migrate" {
  name     = "nestor-migrate"
  location = var.region

  template {
    template {
      service_account = google_service_account.runtime.email

      containers {
        image = local.image
        args  = ["alembic", "upgrade", "head"]

        env {
          name  = "INSTANCE_CONNECTION_NAME"
          value = google_sql_database_instance.main.connection_name
        }
        env {
          name  = "DB_USER"
          value = local.runtime_db_user
        }
        env {
          name  = "DB_NAME"
          value = google_sql_database.app.name
        }
        # The 0005 GRANT reads this to grant the space-scoped privileges to the
        # runtime SA IAM DB user (OQ1/A5). Same value as DB_USER.
        env {
          name  = "RUNTIME_DB_USER"
          value = local.runtime_db_user
        }
      }
    }
  }

  depends_on = [
    google_project_iam_member.runtime_cloudsql_client,
    google_project_iam_member.runtime_cloudsql_instance_user,
    google_sql_user.runtime,
    # WR-04: the Job's execution (alembic upgrade head -> 0005 GRANT) runs against
    # DB_NAME, so the application database must exist before the Job is created.
    # The env references above do not create an implicit edge to the database, so
    # declare it explicitly to keep the create-ordering graph complete.
    google_sql_database.app,
  ]
}

# ------------------------------------------------ Cloud Run superadmin-seed JOB (D-05)
# One-shot first-superadmin bootstrap (Open Q3 / D-05). Same image + same runtime SA
# as the service; overrides the Uvicorn CMD with `python -m scripts.seed_superadmin`
# (mirrors the migration Job's alt-entrypoint pattern). The runtime SA carries
# roles/identitytoolkit.admin (above), so the claim write + IdP user create/lookup
# succeed via ADC -- NO JSON SA key (T-03-15). The SUPERADMIN_PASSWORD is NOT set here
# (never stored in IaC/state); it is supplied at execution time with
# `gcloud run jobs execute ... --update-env-vars SUPERADMIN_PASSWORD=...` (see README).
resource "google_cloud_run_v2_job" "seed_superadmin" {
  name     = "nestor-seed-superadmin"
  location = var.region

  template {
    template {
      service_account = google_service_account.runtime.email

      containers {
        image = local.image
        args  = ["python", "-m", "scripts.seed_superadmin"]

        env {
          name  = "INSTANCE_CONNECTION_NAME"
          value = google_sql_database_instance.main.connection_name
        }
        env {
          name  = "DB_USER"
          value = local.runtime_db_user
        }
        env {
          name  = "DB_NAME"
          value = google_sql_database.app.name
        }
        # The first superadmin's email. The PASSWORD is intentionally absent here and
        # supplied at execute time (T-03-15). GOOGLE_CLOUD_PROJECT is injected by Cloud
        # Run, so the Admin SDK's ADC init resolves the Identity Platform project.
        env {
          name  = "SUPERADMIN_EMAIL"
          value = var.superadmin_email
        }
      }
    }
  }

  depends_on = [
    google_project_iam_member.runtime_cloudsql_client,
    google_project_iam_member.runtime_cloudsql_instance_user,
    google_project_iam_member.runtime_identitytoolkit_admin,
    google_sql_user.runtime,
    # The seed writes the membership row -> the database (and the migrated schema) must
    # exist first; the migration Job must have run before this is executed.
    google_sql_database.app,
  ]
}

# ------------------------------------------------------------- Invoker policy (OQ2)
# Authenticated-only by default (allow_unauthenticated=false): the deployed
# /readyz is reached via `gcloud run services proxy` (T-02-13). Public health-only
# is an explicit opt-in -- this binding is created ONLY when the var is true.
resource "google_cloud_run_v2_service_iam_member" "invoker" {
  count    = var.allow_unauthenticated ? 1 : 0
  name     = google_cloud_run_v2_service.api.name
  location = google_cloud_run_v2_service.api.location
  role     = "roles/run.invoker"
  member   = "allUsers"
}

# -------------------------------------------- Cloud Run FRONTEND service (INFRA-05 / Phase 12)
# The TanStack Start (Nitro node-server) SSR app, containerized and served from Cloud Run
# instead of Cloudflare Workers (D-01 — the auto-generated run.app URL is v1's frontend
# origin; no custom domain). This block MIRRORS google_cloud_run_v2_service.api above with
# the frontend deltas (12-RESEARCH Pattern 4):
#   - scale to ZERO (min_instance_count = 0, D-02 — cold starts accepted, matches the API),
#     max capped at 4.
#   - container_port 8080 with an explicit PORT=8080 env (Nitro node-server reads $PORT).
#   - NO `timeout = "900s"` and NO `resources.cpu_idle = false`: the frontend tier does NO
#     long-lived SSE and NO 90–120s background LLM/Whisper work (those are API concerns),
#     so it keeps the Cloud Run defaults (300s timeout, CPU throttled between requests).
#   - image = local.frontend_image (the `.../nestor/frontend:<tag>` path — SAME Artifact
#     Registry repo as the backend, no new repo). No runtime SA / secrets / DB env: the SSR
#     server serves static + SSR HTML only; every data call goes from the BROWSER directly to
#     nestor-api with a Firebase ID token (the frontend service is NOT an API proxy). All
#     public build-time config (VITE_FIREBASE_*, VITE_API_BASE_URL) is INLINED into the bundle
#     at image-build time via Docker build-args (12-RESEARCH Pattern 2) — never a runtime env
#     here — and NO VITE_SUPABASE_* is ever baked (D-09/D-11 independence).
#
# IaC-DRIFT: Terraform state was never adopted for this project (see the Phase 5/7/8/9/10
# drift notes in DEPLOY-RUNBOOK.md and .planning/STATE.md). This resource — and the allUsers
# invoker binding below — are the INTENDED end-state only; they are INERT until the frontend
# image is built + deployed out-of-band via the Phase-12 gcloud steps in
# infra/DEPLOY-RUNBOOK.md (§ Phase 12). Reconcile via `terraform import` (or keep manual).
resource "google_cloud_run_v2_service" "frontend" {
  name     = var.frontend_service_name
  location = var.region

  template {
    # D-02: scale to ZERO when idle (min_instance_count = 0 — warm-pool knob OFF, no idle
    # cost); max capped at 4. Cold starts are accepted for the SSR tier (matches the API's
    # scale-to-zero posture). No cpu_idle override: the frontend does no request-spawned
    # background work, so the Cloud Run default (CPU throttled between requests) is correct.
    scaling {
      min_instance_count = 0 # scale to zero (D-02)
      max_instance_count = 4
    }

    containers {
      image = local.frontend_image

      # Cloud Run injects PORT (default 8080); the Nitro node-server entry
      # (`node .output/server/index.mjs`) binds $PORT. Declare it explicitly so the
      # container_port and the server bind agree.
      ports {
        container_port = 8080
      }

      # Nitro node-server reads PORT/NITRO_PORT. Set PORT=8080 explicitly to match the
      # container_port above (belt-and-suspenders — Cloud Run also injects PORT at runtime).
      env {
        name  = "PORT"
        value = "8080"
      }
    }
    # Deliberately NO service_account, NO secret env, NO DB/connector env, NO 900s timeout,
    # and NO cpu_idle=false here (see the block header): the SSR frontend is a stateless
    # public web tier that never touches the DB, Secret Manager, or long background work.
  }
}

# Public invoker for the frontend service (A6 / T-12-12 disposition=accept). Unlike the
# API's opt-in `var.allow_unauthenticated` binding above, the frontend is a PUBLIC web app
# and MUST be publicly reachable so a browser can load the SSR HTML + static assets — so it
# gets an UNCONDITIONAL allUsers run.invoker. This does NOT weaken tenant isolation: the
# frontend is SSR-only and does NOT proxy the API; the browser calls nestor-api directly
# with its own Firebase ID token, and the API verifies every token independently (app-level
# auth gates all data). Documented in DEPLOY-RUNBOOK.md § Phase 12.
resource "google_cloud_run_v2_service_iam_member" "frontend_invoker" {
  name     = google_cloud_run_v2_service.frontend.name
  location = google_cloud_run_v2_service.frontend.location
  role     = "roles/run.invoker"
  member   = "allUsers"
}

# ================================================================================
# Phase 13 — Tribunal re-home (deep-research engine into the intake project)
# ================================================================================
# By-construction IaC for the re-homed Tribunal engine (D-01/D-02). This block adds
# the FULL Tribunal footprint alongside the intake resources above:
#   - two Cloud Run services: always-on `tribunal-worker` (min=1, max=5, cpu_idle=false,
#     timeout 3600 — D-04 always-on + D-08 concurrency) and `tribunal-api`
#     (min=0, max=3, timeout 300).
#   - a `tribunal-migrate` Cloud Run Job (alembic upgrade head into the `tribunal` schema).
#   - a 7-year, mode="Unlocked" audit-evidence GCS bucket (D-09 — object retention, NOT
#     Bucket Lock; verified against nestor_pulse_sdk/audit/gcs_blob.py).
#   - six Secret Manager secrets: the three provider keys under the `Nestor_*` names the
#     copied secrets_bootstrap.py reads (D-06), plus DATABASE_URL / DATABASE_URL_WORKER /
#     AUDIT_GCS_BUCKET — each with a resource-scoped secretAccessor to the runtime SA.
#   - two BUILT_IN Cloud SQL users: `app_user` (API) and `worker_user` (the cross-tenant
#     claim role — granted on the `tribunal` schema ONLY, never `nestor`; T-13-09).
#
# DB AUTH TOPOLOGY (RESEARCH Pitfall 5): unlike the intake api (IAM connector), the
# Tribunal services authenticate with a STORED password over asyncpg (DATABASE_URL /
# DATABASE_URL_WORKER secrets). Hence BUILT_IN users + password DSNs here, NOT an
# INSTANCE_CONNECTION_NAME/IAM path. The DSN carries the unix-socket host, so the
# services still attach the Cloud SQL instance (the runbook `--add-cloudsql-instances`).
#
# IaC-DRIFT: Terraform state was never adopted for this project (see the Phase 5/7/8/9/10/12
# drift notes above + in DEPLOY-RUNBOOK.md and .planning/STATE.md). Every resource below —
# and its IAM bindings + secret injections — is the INTENDED end-state only; it is INERT
# until applied out-of-band via the § Phase 13 gcloud steps in infra/DEPLOY-RUNBOOK.md
# (Plan 04, operator-run). Reconcile via `terraform import` (or keep manual).

locals {
  # Tribunal images share the existing `nestor` Artifact Registry repo (no new repo),
  # pathed to the two Tribunal image names and driven by var.tribunal_image_tag
  # (passed on apply, like image_tag/frontend_image_tag).
  tribunal_api_image    = "${var.region}-docker.pkg.dev/${var.project}/${var.repo}/tribunal-api:${var.tribunal_image_tag}"
  tribunal_worker_image = "${var.region}-docker.pkg.dev/${var.project}/${var.repo}/tribunal-worker:${var.tribunal_image_tag}"

  # Audit bucket name: explicit var override, else the project-prefixed default.
  tribunal_audit_bucket_name = var.tribunal_audit_bucket_name != "" ? var.tribunal_audit_bucket_name : "${var.project}-nestor-audit"
}

# ================================================================================
# Phase 14 — dedicated least-privilege Tribunal runtime SA (WR-03 / D-04b)
# ================================================================================
# The WR-03 finding: Phase 13 ran BOTH Tribunal services + the migrate Job on the
# intake `nestor-run` SA (google_service_account.runtime), which also carries
# identitytoolkit.admin, the intake superadmin DB-password secret, and the intake
# uploads bucket. That makes the tribunal-api invoker gate theater — the caller and
# callee SA are the SAME identity, and a compromised Tribunal worker inherits the
# intake admin surfaces. Phase 14 gives Tribunal its OWN least-privilege SA so:
#   1. caller (nestor-run) != callee (tribunal-run) — the invoker gate becomes real
#      and the wrong-SA negative proof (Task 3) is even constructible; and
#   2. a compromised Tribunal worker reaches ONLY the Tribunal secrets + audit bucket,
#      never identitytoolkit.admin / the intake superadmin secret / intake uploads.
#
# LEAST-PRIVILEGE GRANT LIST (the ONLY grants tribunal-run gets):
#   - roles/cloudsql.client (project) — the connector/instance attach for the asyncpg
#     unix-socket DSN. NOT roles/cloudsql.instanceUser: the Tribunal services
#     authenticate with a stored BUILT_IN-user password (Pitfall 5), NOT IAM DB login,
#     so instanceUser (IAM login) is unnecessary.
#   - resource-scoped secretmanager.secretAccessor on the SIX Tribunal secrets ONLY
#     (tribunal_gemini / tribunal_claude / tribunal_openai / tribunal_database_url /
#     tribunal_database_url_worker / tribunal_audit_bucket).
#   - bucket-scoped storage.objectAdmin on the tribunal_audit bucket ONLY.
# Deliberately NOT granted: identitytoolkit.admin, the intake app_superadmin secret,
# the intake uploads bucket — those stay bound to the intake runtime SA alone.
#
# IaC-DRIFT: as with every prior phase, this is the INTENDED end-state, INERT until
# the operator runs the § Phase 14 gcloud steps in infra/DEPLOY-RUNBOOK.md (Plan 04).
resource "google_service_account" "tribunal_run" {
  account_id   = var.tribunal_runtime_sa_id
  display_name = "Tribunal engine runtime (least-priv)"
}

# cloudsql.client ONLY (NOT instanceUser — BUILT_IN-password path, not IAM DB login).
resource "google_project_iam_member" "tribunal_run_cloudsql_client" {
  project = var.project
  role    = "roles/cloudsql.client"
  member  = "serviceAccount:${google_service_account.tribunal_run.email}"
}

# NOTE: the resource-scoped secretAccessor grants on the six Tribunal secrets and the
# tribunal_audit-bucket objectAdmin grant are declared ONCE (below, in the Phase-13
# blocks) and REPOINTED from the intake runtime SA to `tribunal_run.email` in this
# phase — the grants follow the SA that now runs the services/job. See
# google_secret_manager_secret_iam_member.runtime_tribunal_* and
# google_storage_bucket_iam_member.runtime_tribunal_audit_object_admin — their `member`
# is now `google_service_account.tribunal_run.email`. Keeping a single grant per secret
# (repointed) rather than adding a duplicate keeps the least-privilege set exact.

# ---------------------------------------------------- Tribunal BUILT_IN DB users (Pitfall 5)
# `app_user` (API) + `worker_user` (cross-tenant claim role). BUILT_IN password users
# (mirror google_sql_user.app_superadmin above) because the Tribunal services authenticate
# with a stored password over asyncpg, NOT the IAM connector. Passwords are GENERATED (never
# committed literals) and flow only random_password -> the DATABASE_URL{,_WORKER} secret
# versions (composed + seeded out-of-band per the runbook — the *values* here are NOT wired
# into a secret_version resource in IaC, so nothing lands in committed state).
#
# ISOLATION FIREWALL (T-13-09): `worker_user` is granted USAGE + DML on the `tribunal`
# schema ONLY — never the intake `nestor` schema. The actual GRANT lives in Tribunal
# migration 0008 (Plan 02), run by the tribunal-migrate Job under `search_path=tribunal`.
# This resource only CREATES the role; the runbook (Task 2) documents creating both roles
# out-of-band with `gcloud sql users create` before the migrate Job runs.
resource "random_password" "tribunal_app_user" {
  length           = 32
  special          = true
  override_special = "!#%*-_=+:?"
}

resource "random_password" "tribunal_worker_user" {
  length           = 32
  special          = true
  override_special = "!#%*-_=+:?"
}

resource "google_sql_user" "tribunal_app_user" {
  name     = "app_user"
  instance = google_sql_database_instance.main.name
  type     = "BUILT_IN"
  password = random_password.tribunal_app_user.result

  # 13-REVIEW CR-02: the LIVE password was generated and seeded manually
  # (runbook Step 13.d, 2026-07-20) and is embedded in the DATABASE_URL secret.
  # A future `terraform import` + apply must NOT rotate it to this resource's
  # random_password — that would take down all three Tribunal services.
  lifecycle {
    ignore_changes = [password]
  }
}

resource "google_sql_user" "tribunal_worker_user" {
  # worker_user: the cross-tenant claim role. Granted USAGE/DML on the `tribunal`
  # schema ONLY (migration 0008, Plan 02) — NEVER `nestor` (isolation firewall, T-13-09).
  name     = "worker_user"
  instance = google_sql_database_instance.main.name
  type     = "BUILT_IN"
  password = random_password.tribunal_worker_user.result

  # 13-REVIEW CR-02: live password seeded manually into DATABASE_URL_WORKER —
  # never rotate via apply/import (see tribunal_app_user note).
  lifecycle {
    ignore_changes = [password]
  }
}

# ---------------------------------------------------- Tribunal provider key secrets (D-06)
# Three secrets under the EXACT `Nestor_*` names secrets_bootstrap.py reads (no bootstrap
# refactor — RESEARCH Open Q3). Each mirrors the anthropic_api_key trio above: secret
# resource + resource-scoped secretAccessor to the runtime SA. VALUES seeded out-of-band
# per the runbook (drift-honest — no *_version resource here, so no value in committed state,
# T-13-08). Gemini is reseeded from the old project's key (D-06 — all three providers day one).
resource "google_secret_manager_secret" "tribunal_gemini" {
  secret_id = var.tribunal_gemini_secret_id
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_iam_member" "runtime_tribunal_gemini_accessor" {
  secret_id = google_secret_manager_secret.tribunal_gemini.secret_id
  role      = "roles/secretmanager.secretAccessor"
  # Phase 14 (WR-03): repointed from the intake runtime SA to the DEDICATED
  # tribunal-run SA — the grant follows the SA that now runs the Tribunal services.
  member = "serviceAccount:${google_service_account.tribunal_run.email}"
}

resource "google_secret_manager_secret" "tribunal_claude" {
  secret_id = var.tribunal_claude_secret_id
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_iam_member" "runtime_tribunal_claude_accessor" {
  secret_id = google_secret_manager_secret.tribunal_claude.secret_id
  role      = "roles/secretmanager.secretAccessor"
  # Phase 14 (WR-03): repointed to the dedicated tribunal-run SA.
  member = "serviceAccount:${google_service_account.tribunal_run.email}"
}

resource "google_secret_manager_secret" "tribunal_openai" {
  secret_id = var.tribunal_openai_secret_id
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_iam_member" "runtime_tribunal_openai_accessor" {
  secret_id = google_secret_manager_secret.tribunal_openai.secret_id
  role      = "roles/secretmanager.secretAccessor"
  # Phase 14 (WR-03): repointed to the dedicated tribunal-run SA.
  member = "serviceAccount:${google_service_account.tribunal_run.email}"
}

# ---------------------------------------------------- Tribunal DB URL + bucket secrets
# DATABASE_URL (app_user, API) + DATABASE_URL_WORKER (worker_user) — asyncpg unix-socket
# DSNs read from the process env by db/base.py. Plus AUDIT_GCS_BUCKET (the bucket name).
# Same drift-honest handling: resource + scoped accessor in IaC; VALUE seeded out-of-band
# per the runbook (T-13-08 — the DSNs carry the generated BUILT_IN-user passwords, so they
# MUST NOT enter committed state; they are composed + `gcloud secrets versions add`-ed by hand).
resource "google_secret_manager_secret" "tribunal_database_url" {
  secret_id = var.tribunal_database_url_secret_id
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_iam_member" "runtime_tribunal_database_url_accessor" {
  secret_id = google_secret_manager_secret.tribunal_database_url.secret_id
  role      = "roles/secretmanager.secretAccessor"
  # Phase 14 (WR-03): repointed to the dedicated tribunal-run SA.
  member = "serviceAccount:${google_service_account.tribunal_run.email}"
}

resource "google_secret_manager_secret" "tribunal_database_url_worker" {
  secret_id = var.tribunal_database_url_worker_secret_id
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_iam_member" "runtime_tribunal_database_url_worker_accessor" {
  secret_id = google_secret_manager_secret.tribunal_database_url_worker.secret_id
  role      = "roles/secretmanager.secretAccessor"
  # Phase 14 (WR-03): repointed to the dedicated tribunal-run SA.
  member = "serviceAccount:${google_service_account.tribunal_run.email}"
}

resource "google_secret_manager_secret" "tribunal_audit_bucket" {
  secret_id = var.tribunal_audit_bucket_secret_id
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_iam_member" "runtime_tribunal_audit_bucket_accessor" {
  secret_id = google_secret_manager_secret.tribunal_audit_bucket.secret_id
  role      = "roles/secretmanager.secretAccessor"
  # Phase 14 (WR-03): repointed to the dedicated tribunal-run SA.
  member = "serviceAccount:${google_service_account.tribunal_run.email}"
}

# ---------------------------------------------------- Tribunal audit-evidence bucket (D-09)
# The immutable audit-body store the hash-chain writes to. Mirrors google_storage_bucket.uploads
# above (uniform BLA + public-access-prevention enforced, force_destroy=false) BUT adds the D-09
# legal retention: 7-YEAR, mode="Unlocked" OBJECT retention.
#
# D-09 — OBJECT retention, NOT Bucket Lock (verified against
# nestor_pulse_sdk/audit/gcs_blob.py, Pitfall 7): the engine sets per-object
# `blob.retention.mode = "Unlocked"` + `retain_until_time = now + 7y` on every upload.
# For the bucket to ACCEPT per-object retention its `retention_policy` must be absent-or-unlocked
# and object retention must be ENABLED at create time. We therefore:
#   - set `enable_object_retention = true` (turns on the per-object Object Retention API the
#     engine uses) and
#   - DELIBERATELY DO NOT declare a bucket-level `retention_policy { is_locked = true }`
#     (that is Bucket Lock — irreversible, FORBIDDEN for this project, D-09).
# The literal 7-year duration lives on each object (gcs_blob.py `_RETENTION_YEARS = 7`), so no
# bucket-level lifecycle rule encodes it — retention is per-object + Unlocked (reversible).
resource "google_storage_bucket" "tribunal_audit" {
  name     = local.tribunal_audit_bucket_name
  location = var.region

  uniform_bucket_level_access = true       # IAM-only access control (no per-object ACLs)
  public_access_prevention    = "enforced" # zero public objects — audit bodies are never public

  # D-09: turn ON the Object Retention API so gcs_blob.py's per-object
  # blob.retention.mode="Unlocked" + retain_until_time = now+7y is honored. This is the
  # per-object mechanism — NOT a bucket-level retention_policy (which would be Bucket Lock).
  enable_object_retention = true

  # DELIBERATELY NO `retention_policy` block: a bucket-level retention_policy with
  # is_locked = true is Bucket Lock (permanent, irreversible) — FORBIDDEN (D-09). Retention
  # is applied per-object with mode="Unlocked" (reversible) by the engine at upload time.

  force_destroy = false # never auto-wipe the legal audit chain on destroy
}

# Bucket-scoped storage.objectAdmin for the runtime SA (least privilege, mirror
# runtime_object_admin above). objectAdmin (not objectViewer/objectCreator) is required
# because gcs_blob.py both uploads bodies AND patches per-object retention (blob.patch()).
resource "google_storage_bucket_iam_member" "runtime_tribunal_audit_object_admin" {
  bucket = google_storage_bucket.tribunal_audit.name
  role   = "roles/storage.objectAdmin"
  # Phase 14 (WR-03): repointed from the intake runtime SA to the dedicated tribunal-run
  # SA — objectAdmin (upload + patch retention) follows the SA that now runs the engine.
  member = "serviceAccount:${google_service_account.tribunal_run.email}"
}

# ---------------------------------------------------- tribunal-worker service (D-04/D-08)
# Always-on poll-loop worker. Mirrors google_cloud_run_v2_service.api but: min=1 (always-on,
# vs intake api's 0), max=5 (D-08 — the per-run advisory lock + SKIP-LOCKED make >1 poller
# safe), cpu_idle=false (no-cpu-throttling — the worker polls Postgres on its own schedule and
# runs ~35-min deep-research pipelines off the request path), timeout 3600s. No unauthenticated
# invoker (no allUsers binding — background worker, no public HTTP). Secrets: DATABASE_URL is
# sourced from DATABASE_URL_WORKER (worker_user, the cross-tenant claim role) + the three
# Nestor_* provider keys. NESTOR_TRIBUNAL_UNCAPPED=1 (D-07 — uncapped this phase).
resource "google_cloud_run_v2_service" "tribunal_worker" {
  name     = var.tribunal_worker_service_name
  location = var.region

  template {
    # Phase 14 (WR-03/D-04b): the DEDICATED least-privilege Tribunal SA, NOT the intake
    # runtime SA — a compromised worker reaches only the Tribunal secrets + audit bucket.
    service_account = google_service_account.tribunal_run.email

    # Long timeout so a full deep-research run (~35 min) is not severed (old deploy: 3600).
    timeout = "3600s"

    scaling {
      min_instance_count = 1                                 # D-04: always-on (intake api uses 0)
      max_instance_count = var.tribunal_worker_max_instances # D-08: size for 5+ (default 5)
    }

    # 13-REVIEW CR-03: the asyncpg unix-socket DSN needs the Cloud SQL volume —
    # gcloud's --add-cloudsql-instances does this implicitly at deploy.
    volumes {
      name = "cloudsql"
      cloud_sql_instance {
        instances = [google_sql_database_instance.main.connection_name]
      }
    }

    containers {
      image = local.tribunal_worker_image

      volume_mounts {
        name       = "cloudsql"
        mount_path = "/cloudsql"
      }

      # No-cpu-throttling: CPU allocated even with no inbound HTTP so the poll loop +
      # long pipeline run between requests (the native equivalent of the gen1
      # `run.googleapis.com/cpu-throttling=false` annotation the old deploy script set).
      resources {
        cpu_idle = false
      }

      # D-07: uncapped this phase (matches the old deploy-worker.sh env).
      env {
        name  = "NESTOR_TRIBUNAL_UNCAPPED"
        value = "1"
      }
      # Stale-claim reclaim window (calibrated in Phase 16; carried as plain non-secret env).
      env {
        name  = "NESTOR_WORKER_STALE_MINUTES"
        value = var.tribunal_worker_stale_minutes
      }
      # AUDIT_GCS_BUCKET: the audit-body bucket name. Injected from the secret purely for
      # uniformity with the DB/provider secrets (the value is the non-secret bucket name).
      env {
        name = "AUDIT_GCS_BUCKET"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.tribunal_audit_bucket.secret_id
            version = "latest"
          }
        }
      }
      # DATABASE_URL <- DATABASE_URL_WORKER (worker_user, cross-tenant claim role). asyncpg
      # DSN read by db/base.py from the process env. NEVER app_user's DATABASE_URL.
      env {
        name = "DATABASE_URL"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.tribunal_database_url_worker.secret_id
            version = "latest"
          }
        }
      }
      # Provider keys under the Nestor_* names secrets_bootstrap.py reads (D-06).
      env {
        name = "ANTHROPIC_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.tribunal_claude.secret_id
            version = "latest"
          }
        }
      }
      env {
        name = "GOOGLE_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.tribunal_gemini.secret_id
            version = "latest"
          }
        }
      }
      env {
        name = "OPENAI_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.tribunal_openai.secret_id
            version = "latest"
          }
        }
      }
    }
  }

  depends_on = [
    # Phase 14 (WR-03): cloudsql.client now follows the dedicated tribunal-run SA
    # (NOT instanceUser — BUILT_IN-password path, not IAM DB login).
    google_project_iam_member.tribunal_run_cloudsql_client,
    # worker_user + the worker's secrets/grants + the audit bucket grant must exist before
    # the worker boots, or native secret_key_ref resolution / the first audit upload fails.
    # These grants are now bound to tribunal-run (repointed this phase).
    google_sql_user.tribunal_worker_user,
    google_secret_manager_secret_iam_member.runtime_tribunal_database_url_worker_accessor,
    google_secret_manager_secret_iam_member.runtime_tribunal_claude_accessor,
    google_secret_manager_secret_iam_member.runtime_tribunal_gemini_accessor,
    google_secret_manager_secret_iam_member.runtime_tribunal_openai_accessor,
    google_secret_manager_secret_iam_member.runtime_tribunal_audit_bucket_accessor,
    google_storage_bucket_iam_member.runtime_tribunal_audit_object_admin,
  ]
}

# ---------------------------------------------------- tribunal-api service (request-response)
# Mirrors google_cloud_run_v2_service.api: min=0, max=3, timeout 300. Secrets: DATABASE_URL is
# sourced from DATABASE_URL (app_user, tenant-scoped) + the three Nestor_* provider keys +
# AUDIT_GCS_BUCKET. NEVER an allUsers invoker here: Phase 14 binds run.invoker
# UNCONDITIONALLY to ONLY the intake runtime SA (see tribunal_api_invoker below — deliberately
# NOT gated on var.allow_unauthenticated; the D-04 outer gate).
resource "google_cloud_run_v2_service" "tribunal_api" {
  name     = var.tribunal_api_service_name
  location = var.region

  template {
    # Phase 14 (WR-03/D-04b): the DEDICATED least-privilege Tribunal SA (see the worker).
    service_account = google_service_account.tribunal_run.email

    timeout = "300s"

    scaling {
      min_instance_count = 0 # scale to zero (matches intake api)
      max_instance_count = 3 # request-response tier
    }

    # 13-REVIEW CR-03: asyncpg unix-socket DSN needs the Cloud SQL volume.
    volumes {
      name = "cloudsql"
      cloud_sql_instance {
        instances = [google_sql_database_instance.main.connection_name]
      }
    }

    containers {
      image = local.tribunal_api_image

      volume_mounts {
        name       = "cloudsql"
        mount_path = "/cloudsql"
      }

      ports {
        container_port = 8080
      }

      env {
        name  = "NESTOR_TRIBUNAL_UNCAPPED"
        value = "1"
      }
      # Phase 14 seam env vars (both PLAIN non-secret — read by InternalCallerProvider,
      # 14-01-SUMMARY). TRIBUNAL_SERVICE_URL is tribunal-api's OWN run.app URL WITHOUT a
      # path (the OIDC audience it verifies its token's aud against — Pitfall 4);
      # INTAKE_RUNTIME_SA_EMAIL is the intake nestor-run SA the caller email must match.
      # IaC-DRIFT: inert until the runbook `--update-env-vars TRIBUNAL_SERVICE_URL=<captured
      # describe url>,INTAKE_RUNTIME_SA_EMAIL=...` (§ Phase 14, Step 14.d) sets them live —
      # the URL cannot be known until the service is first deployed + described.
      env {
        name  = "TRIBUNAL_SERVICE_URL"
        value = var.tribunal_service_url
      }
      env {
        name  = "INTAKE_RUNTIME_SA_EMAIL"
        value = google_service_account.runtime.email
      }
      env {
        name = "AUDIT_GCS_BUCKET"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.tribunal_audit_bucket.secret_id
            version = "latest"
          }
        }
      }
      # DATABASE_URL <- DATABASE_URL (app_user, tenant-scoped — NOT the worker DSN).
      env {
        name = "DATABASE_URL"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.tribunal_database_url.secret_id
            version = "latest"
          }
        }
      }
      env {
        name = "ANTHROPIC_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.tribunal_claude.secret_id
            version = "latest"
          }
        }
      }
      env {
        name = "GOOGLE_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.tribunal_gemini.secret_id
            version = "latest"
          }
        }
      }
      env {
        name = "OPENAI_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.tribunal_openai.secret_id
            version = "latest"
          }
        }
      }
    }
  }

  depends_on = [
    # Phase 14 (WR-03): cloudsql.client now follows the dedicated tribunal-run SA.
    google_project_iam_member.tribunal_run_cloudsql_client,
    google_sql_user.tribunal_app_user,
    google_secret_manager_secret_iam_member.runtime_tribunal_database_url_accessor,
    google_secret_manager_secret_iam_member.runtime_tribunal_claude_accessor,
    google_secret_manager_secret_iam_member.runtime_tribunal_gemini_accessor,
    google_secret_manager_secret_iam_member.runtime_tribunal_openai_accessor,
    google_secret_manager_secret_iam_member.runtime_tribunal_audit_bucket_accessor,
    google_storage_bucket_iam_member.runtime_tribunal_audit_object_admin,
  ]
}

# ---------------------------------------------------- tribunal-api invoker (D-04 outer gate)
# Phase 14 (WR-03/D-04): the ONLY principal allowed to invoke tribunal-api is the intake
# nestor-run SA — an UNCONDITIONAL run.invoker binding (NOT gated on allow_unauthenticated,
# and NOT allUsers). The service stays --no-allow-unauthenticated: any browser / third party
# / wrong-SA caller is rejected at the Cloud Run IAM gate (T-14-12), and even a mis-set IAM
# binding is caught by the InternalCallerProvider inner gate (Plan 01, T-14-13). This gate is
# only MEANINGFUL because Phase 14 gave Tribunal a dedicated SA — caller (nestor-run) != callee
# (tribunal-run) — so the wrong-SA negative proof (Task 3) is even constructible.
resource "google_cloud_run_v2_service_iam_member" "tribunal_api_invoker" {
  name     = google_cloud_run_v2_service.tribunal_api.name
  location = google_cloud_run_v2_service.tribunal_api.location
  role     = "roles/run.invoker"
  member   = "serviceAccount:${google_service_account.runtime.email}"
}

# ---------------------------------------------------- tribunal-migrate JOB (alembic upgrade head)
# Mirrors google_cloud_run_v2_job.migrate: same runtime SA, override CMD with
# `alembic upgrade head`. Runs the Tribunal alembic line into the `tribunal` SCHEMA (the
# env.py edits in Plan 02 set version_table_schema=tribunal + search_path=tribunal so
# unqualified CREATE TABLE / the 0008 GRANTs land in `tribunal`, never colliding with the
# intake `alembic_version`). Uses DATABASE_URL (app_user, asyncpg) — NOT the IAM connector
# env (Pitfall 5). Depends on app_user existing; the runbook creates the roles + notes the
# `CREATE SCHEMA tribunal` happens via env.py at first migrate.
resource "google_cloud_run_v2_job" "tribunal_migrate" {
  name     = "tribunal-migrate"
  location = var.region

  template {
    template {
      # Phase 14 (WR-03/D-04b): the migrate Job runs as the DEDICATED tribunal-run SA
      # too (it touches only the tribunal schema + the DATABASE_URL secret).
      service_account = google_service_account.tribunal_run.email

      # 13-REVIEW CR-03: the asyncpg unix-socket DSN (host=/cloudsql/...) needs
      # the Cloud SQL volume mounted — gcloud's --set-cloudsql-instances does
      # this implicitly; the declared end-state must too.
      volumes {
        name = "cloudsql"
        cloud_sql_instance {
          instances = [google_sql_database_instance.main.connection_name]
        }
      }

      containers {
        image = local.tribunal_api_image
        # 13-REVIEW CR-03: `alembic upgrade head` from /app FAILS ("No
        # 'script_location' key") — alembic.ini lives in /app/nestor_pulse_sdk
        # with a cwd-relative script_location. Proven-live form (execution
        # tribunal-migrate-sc64g, 2026-07-20):
        command = ["sh"]
        args    = ["-c", "cd /app/nestor_pulse_sdk && alembic upgrade head"]

        volume_mounts {
          name       = "cloudsql"
          mount_path = "/cloudsql"
        }

        # asyncpg DSN (app_user) — NOT INSTANCE_CONNECTION_NAME/IAM (Pitfall 5). The migrate
        # Job runs the Tribunal alembic line under search_path=tribunal (env.py, Plan 02).
        env {
          name = "DATABASE_URL"
          value_source {
            secret_key_ref {
              secret  = google_secret_manager_secret.tribunal_database_url.secret_id
              version = "latest"
            }
          }
        }
      }
    }
  }

  depends_on = [
    # Phase 14 (WR-03): cloudsql.client follows the dedicated tribunal-run SA.
    google_project_iam_member.tribunal_run_cloudsql_client,
    # app_user + its DATABASE_URL secret grant (now bound to tribunal-run) must exist
    # before the Job runs alembic.
    google_sql_user.tribunal_app_user,
    google_secret_manager_secret_iam_member.runtime_tribunal_database_url_accessor,
  ]
}
