# Input variables for the Nestor Intake GCP footprint.
#
# Defaults encode the resolved Phase-2 open questions:
#   - region          -> europe-west1 (OQ3: single EU region for the NL/FR/EN base)
#   - tier            -> db-custom-1-3840 (A4: 3.75 GB, default max_connections=100,
#                        comfortably above the D-04 connection-math ceiling of ~30)
#   - db_name         -> nestor (the application database)
#   - allow_unauthenticated -> false (OQ2: authenticated invoker by default; the
#                        deployed /readyz is reached via `gcloud run services proxy`.
#                        Public health-only is an explicit opt-in.)
# image_tag has no default: the deploy is a two-step (apply -> build/push -> apply)
# and the user passes the real tag on the second apply (see infra/README.md).

variable "project" {
  description = "Target GCP project ID."
  type        = string
}

variable "region" {
  description = "GCP region for Cloud SQL, Artifact Registry, and Cloud Run (OQ3)."
  type        = string
  default     = "europe-west1"
}

variable "tier" {
  description = "Cloud SQL machine tier. db-custom-1-3840 -> default max_connections=100 (A4/D-04)."
  type        = string
  default     = "db-custom-1-3840"
}

variable "repo" {
  description = "Artifact Registry Docker repository ID for the backend image."
  type        = string
  default     = "nestor"
}

variable "image_tag" {
  description = "Backend image tag in Artifact Registry (passed on the second apply; see README)."
  type        = string
}

variable "db_name" {
  description = "Cloud SQL application database name."
  type        = string
  default     = "nestor"
}

variable "instance_name" {
  description = "Cloud SQL instance name."
  type        = string
  default     = "nestor-pg"
}

variable "service_name" {
  description = "Cloud Run service name."
  type        = string
  default     = "nestor-api"
}

variable "runtime_sa_id" {
  description = "Account ID (local part) for the Cloud Run runtime service account."
  type        = string
  default     = "nestor-run"
}

variable "superadmin_email" {
  description = "Email of the first superadmin bootstrapped by the nestor-seed-superadmin Cloud Run Job (D-05). The password is supplied at execution time (--update-env-vars SUPERADMIN_PASSWORD=...), never stored in IaC/state (T-03-15)."
  type        = string
  default     = "yanick@agenic.be"
}

variable "superadmin_db_secret_id" {
  description = "Secret Manager secret ID holding the BUILT_IN app_superadmin Cloud SQL user's generated password (Path B / D-05a). This is the SINGLE deliberate stored DB credential — the password is generated by random_password and lives only in Secret Manager; the Cloud Run service env carries the secret RESOURCE NAME (projects/<p>/secrets/<id>/versions/latest), never the value (T-04-16). The app_superadmin user is the EXACT literal the 0003 `current_user='app_superadmin'` bypass policy matches (T-04-20)."
  type        = string
  default     = "nestor-app-superadmin-db-password"
}

variable "allow_unauthenticated" {
  description = "If true, allow public (allUsers) invocation of the Cloud Run service. Default false = authenticated invoker only; verify /readyz via `gcloud run services proxy` (OQ2)."
  type        = bool
  default     = false
}

# ------------------------------------------------ Frontend Cloud Run service (INFRA-05 / Phase 12)
# The new TanStack Start (Nitro node-server) SSR service that replaces the Cloudflare Workers
# deploy (D-01). Mirrors `service_name` / `image_tag` above. The frontend image shares the
# `nestor` Artifact Registry repo (var.repo) — path `.../nestor/frontend:<tag>` — so no new
# repo variable is needed. Unlike the backend, this tier gets an UNCONDITIONAL allUsers
# invoker (public web app, A6) — there is no allow_unauthenticated toggle for it.

variable "frontend_service_name" {
  description = "Cloud Run service name for the frontend SSR container (INFRA-05 / D-01). The frontend image lives in the same `nestor` Artifact Registry repo as the backend (path `.../nestor/frontend:<tag>`)."
  type        = string
  default     = "nestor-frontend"
}

variable "frontend_image_tag" {
  description = "Frontend image tag in Artifact Registry (path `.../nestor/frontend:<tag>`), passed on apply exactly like `image_tag` — the deploy is a two-step (build/push via Cloud Build -> deploy). No default: the user supplies the real tag per infra/DEPLOY-RUNBOOK.md § Phase 12."
  type        = string
}

# ------------------------------------------ Frontend build-time public config (INFRA-05 / Phase 12)
# The `VITE_*` values baked into the frontend bundle at IMAGE-BUILD time via Docker build-args
# (12-RESEARCH Pattern 2 — `VITE_*` vars are inlined by `vite build`, NOT read at runtime). They
# are DELIBERATELY not runtime Cloud Run envs: the frontend service reads none of them at boot.
# These variables exist to DOCUMENT the build-arg surface by construction (D-07); they are
# IaC-drift-inert until the runbook Cloud Build step (§ Phase 12, Step 12.3) supplies them as
# `--substitutions`. All are PUBLIC by design (the Firebase web apiKey is a public project
# identifier, NOT a secret). VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY are INTENTIONALLY ABSENT
# — never set at build so the env-guarded supabase.ts client stays null (D-09/D-11 independence).

variable "vite_api_base_url" {
  description = "Frontend build-arg VITE_API_BASE_URL — the live nestor-api origin the browser calls directly with a Firebase ID token. Public, non-secret. IaC-drift-inert until the Cloud Build `--substitutions` step (§ Phase 12, Step 12.3) supplies it; default \"\"."
  type        = string
  default     = ""
}

variable "vite_firebase_api_key" {
  description = "Frontend build-arg VITE_FIREBASE_API_KEY — the Firebase web apiKey, a PUBLIC project identifier (NOT a secret/credential). IaC-drift-inert until the Cloud Build `--substitutions` step supplies it; default \"\"."
  type        = string
  default     = ""
}

variable "vite_firebase_auth_domain" {
  description = "Frontend build-arg VITE_FIREBASE_AUTH_DOMAIN — the Firebase auth domain (public). IaC-drift-inert until the Cloud Build `--substitutions` step supplies it; default \"\"."
  type        = string
  default     = ""
}

variable "vite_firebase_project_id" {
  description = "Frontend build-arg VITE_FIREBASE_PROJECT_ID — the Firebase/GCP project id (public). IaC-drift-inert until the Cloud Build `--substitutions` step supplies it; default \"\"."
  type        = string
  default     = ""
}

# ---------------------------------------------------- Frontend origins (WR-02 / Phase 9)
# The browser origin allowlist for the app frontend (Cloudflare Workers / localhost). Used
# BOTH by the Cloud Run CORS middleware (CORS_ALLOWED_ORIGINS env, set out-of-band per the
# runbook) AND by the uploads-bucket CORS policy below: FinalReportBlock / ResearchResultsPanel
# `fetch()` the signed GCS URL directly from the app origin, so `storage.googleapis.com` must
# echo Access-Control-Allow-Origin for these origins or the browser blocks the read (WR-02).
# Default is empty => NO cors block emitted (no broadening); set to the real frontend origins.
variable "cors_allowed_origins" {
  description = "Browser origins allowed to fetch() signed URLs from the uploads bucket (mirror of the Cloud Run CORS_ALLOWED_ORIGINS allowlist). Empty => no bucket CORS policy (WR-02)."
  type        = list(string)
  default     = []
}

# ---------------------------------------------------- AI provider keys (D-07 / Phase 7)
# The LLM (Anthropic) + embedding/Whisper (OpenAI) credentials. Each is a Secret
# Manager secret whose RESOURCE is declared in IaC, but whose VALUE (the version
# payload) is seeded out-of-band per the deploy runbook by default — the key never
# lands in committed IaC/state (T-7-05). The Cloud Run service env injects them
# natively via value_source.secret_key_ref (NOT a runtime access_secret_version
# call) — they have no import-cycle reason to runtime-fetch (unlike the superadmin
# password). The keys are read at call time by the AI seam and are NEVER logged.

variable "anthropic_api_key_secret_id" {
  description = "Secret Manager secret ID holding ANTHROPIC_API_KEY (Anthropic LLM credential, D-07). The secret RESOURCE + the runtime SA's scoped secretAccessor grant are declared in IaC; the VALUE (version payload) is added out-of-band per infra/DEPLOY-RUNBOOK.md (default: no Terraform-managed version), so the key never lands in committed state (T-7-05)."
  type        = string
  default     = "nestor-anthropic-api-key"
}

variable "openai_api_key_secret_id" {
  description = "Secret Manager secret ID holding OPENAI_API_KEY (OpenAI embedding + Whisper credential, D-07). Same handling as anthropic_api_key_secret_id: resource + secretAccessor in IaC, value seeded out-of-band per the runbook (T-7-05)."
  type        = string
  default     = "nestor-openai-api-key"
}

variable "anthropic_api_key" {
  description = "Optional ANTHROPIC_API_KEY VALUE to seed the secret version at apply time. Default \"\" => Terraform creates NO version (add it manually via `gcloud secrets versions add` per DEPLOY-RUNBOOK.md — the drift-honest default). When non-empty the value is written to a secret version and is then in Terraform state, so prefer the manual path in shared environments (T-7-05)."
  type        = string
  default     = ""
  sensitive   = true
}

variable "openai_api_key" {
  description = "Optional OPENAI_API_KEY VALUE to seed the secret version at apply time. Same semantics as anthropic_api_key: default \"\" => no Terraform-managed version (seed manually per the runbook). Non-empty => stored in state, so prefer the manual path (T-7-05)."
  type        = string
  default     = ""
  sensitive   = true
}

# ---------------------------------------------------- Transactional email (D-13 / Phase 10)
# The Resend transactional-email credential — the ONLY new secret Phase 10 adds. The
# `agenic.be` sender domain is already verified. Same drift-honest handling as the AI
# provider keys: the secret RESOURCE + the runtime SA's scoped secretAccessor grant are
# declared in IaC, but the VALUE (version payload) is seeded out-of-band per the deploy
# runbook by default (T-10-04) — the key never lands in committed IaC/state. The Cloud Run
# service env injects it natively via value_source.secret_key_ref; the mail module reads
# RESEND_API_KEY from the process env at call time and must NEVER log it.

variable "resend_api_key_secret_id" {
  description = "Secret Manager secret ID holding RESEND_API_KEY (Resend transactional-email credential, D-13). The secret RESOURCE + the runtime SA's scoped secretAccessor grant are declared in IaC; the VALUE (version payload) is added out-of-band per infra/DEPLOY-RUNBOOK.md (default: no Terraform-managed version), so the key never lands in committed state (T-10-04)."
  type        = string
  default     = "nestor-resend-api-key"
}

variable "resend_api_key" {
  description = "Optional RESEND_API_KEY VALUE to seed the secret version at apply time. Default \"\" => Terraform creates NO version (add it manually via `gcloud secrets versions add` per DEPLOY-RUNBOOK.md — the drift-honest default). When non-empty the value is written to a secret version and is then in Terraform state, so prefer the manual path in shared environments (T-10-04)."
  type        = string
  default     = ""
  sensitive   = true
}

# ---------------------------------------------------- Mail non-secret config (D-08 / Phase 10)
# Two PLAIN (non-secret) Cloud Run env vars the mail module reads at call time:
#   - NESTOR_ADMIN_EMAIL -> Settings.nestor_admin_email (D-08): the ops address that
#     receives the admin_validated notification.
#   - APP_BASE_URL -> Settings.app_base_url: the origin used to build mail CTA links and
#     the logo asset URL (closes the Phase 9 D-07a handoff — no more public Supabase URL).
# Both default "" and are IaC-DRIFT-inert until the runbook `--update-env-vars` step sets
# them live (mirror the STORAGE_BUCKET drift semantics).

variable "nestor_admin_email" {
  description = "Ops address that receives the admin_validated mail notification (D-08 -> Settings.nestor_admin_email). Plain non-secret Cloud Run env; default \"\" and IaC-drift-inert until the runbook `--update-env-vars NESTOR_ADMIN_EMAIL=...` step sets it live (Phase 10)."
  type        = string
  default     = ""
}

variable "app_base_url" {
  description = "Deployed frontend origin used to build mail CTA links + the logo asset URL (-> Settings.app_base_url, D-15). Plain non-secret Cloud Run env; default \"\" and IaC-drift-inert until the runbook `--update-env-vars APP_BASE_URL=...` step sets it live (Phase 10)."
  type        = string
  default     = ""
}

# ================================================================================
# Phase 13 — Tribunal re-home (deep-research engine into the intake project)
# ================================================================================
# The re-homed Tribunal engine (from the old standalone project-cb01b861) runs as
# TWO new Cloud Run resources in THIS intake project alongside nestor-api: an
# always-on `tribunal-worker` (min=1, max=5 — D-08 concurrency via the per-run
# advisory lock + SKIP-LOCKED) and a request-response `tribunal-api` (min=0, max=3).
# A one-shot `tribunal-migrate` Job runs the Tribunal alembic line into a SEPARATE
# `tribunal` Postgres SCHEMA (never `nestor`). The engine reads its provider keys
# under the `Nestor_*` secret names its copied `secrets_bootstrap.py` already expects
# (D-06 / RESEARCH Open Q3 — no bootstrap refactor). The audit chain persists to a
# dedicated GCS bucket with 7-year per-object retention, mode="Unlocked" (D-09).
#
# DB topology (RESEARCH Pitfall 5): the Tribunal services authenticate with a
# STORED password over asyncpg (the `DATABASE_URL` / `DATABASE_URL_WORKER` secrets),
# NOT the intake IAM-connector path — so `app_user` / `worker_user` are BUILT_IN
# Cloud SQL users (mirror `app_superadmin`), not CLOUD_IAM_SERVICE_ACCOUNT users.
#
# IaC-DRIFT: as with every prior phase, `terraform apply` is blocked on the dev box
# (no Python/Docker/terraform) — these variables + the resources they drive are the
# INTENDED end-state, INERT until the operator runs the § Phase 13 gcloud steps in
# infra/DEPLOY-RUNBOOK.md (Plan 04). Every value is enumerated in that runbook.

variable "tribunal_worker_service_name" {
  description = "Cloud Run service name for the always-on Tribunal worker (poll loop, min=1/max=5 — D-04/D-08)."
  type        = string
  default     = "tribunal-worker"
}

variable "tribunal_api_service_name" {
  description = "Cloud Run service name for the request-response Tribunal API (min=0/max=3)."
  type        = string
  default     = "tribunal-api"
}

variable "tribunal_worker_max_instances" {
  description = "Max instances for the Tribunal worker (D-08 — sized for 5+ concurrent runs; the per-run advisory lock + SKIP-LOCKED make multiple pollers safe)."
  type        = number
  default     = 5
}

variable "tribunal_worker_stale_minutes" {
  description = "NESTOR_WORKER_STALE_MINUTES for the worker — how long a `running` claim may go without a heartbeat before another poller may re-claim it. Calibrated in Phase 16; carried here as a plain non-secret env (matches the old deploy script's default 60)."
  type        = string
  default     = "60"
}

variable "tribunal_image_tag" {
  description = "Tribunal image tag in the `nestor` Artifact Registry repo (paths `.../nestor/tribunal-api:<tag>` and `.../nestor/tribunal-worker:<tag>`). Passed on apply exactly like `image_tag`; no default — the operator supplies the real tag per infra/DEPLOY-RUNBOOK.md § Phase 13 after the Cloud Build step."
  type        = string
  default     = ""
}

# ---------------------------------------------------- Tribunal provider secrets (D-06)
# Reseeded under the EXACT names the copied `secrets_bootstrap.py` reads
# (`Nestor_Claude` -> ANTHROPIC_API_KEY, `Nestor_OpenAI` -> OPENAI_API_KEY,
# `Nestor_Gemini` -> GOOGLE_API_KEY). Same drift-honest handling as the intake AI
# keys: the secret RESOURCE + the runtime SA's resource-scoped secretAccessor are
# in IaC, but the VALUE is seeded out-of-band per the runbook (T-13-08). Note these
# are DISTINCT secret ids from the intake `nestor-anthropic-api-key` /
# `nestor-openai-api-key` — the Tribunal engine reads the `Nestor_*` names verbatim.

variable "tribunal_gemini_secret_id" {
  description = "Secret Manager secret ID for Tribunal's GOOGLE_API_KEY (Gemini — D-06, the third provider arm). Read by secrets_bootstrap.py as `Nestor_Gemini`. Value reseeded out-of-band from the old project's key per the runbook (T-13-08)."
  type        = string
  default     = "Nestor_Gemini"
}

variable "tribunal_claude_secret_id" {
  description = "Secret Manager secret ID for Tribunal's ANTHROPIC_API_KEY. Read by secrets_bootstrap.py as a `Nestor_*` name verbatim. DISTINCT from the intake `nestor-anthropic-api-key` (no bootstrap refactor, RESEARCH Open Q3). Default moved `Nestor_Claude` -> `Nestor_Claude2` by operator decision 2026-07-27: Claude2 is the credit-bearing key, and all three services (tribunal-api, tribunal-worker, nestor-api) were repointed to it in § Phase 15.2 Step 15.2.e."
  type        = string
  default     = "Nestor_Claude2"
}

variable "tribunal_openai_secret_id" {
  description = "Secret Manager secret ID for Tribunal's OPENAI_API_KEY. Read by secrets_bootstrap.py as `Nestor_OpenAI`. DISTINCT from the intake `nestor-openai-api-key`."
  type        = string
  default     = "Nestor_OpenAI"
}

# ---------------------------------------------------- Tribunal DB URL secrets (asyncpg)
# The two stored-credential DSNs the Tribunal services read from the process env
# (db/base.py reads DATABASE_URL directly). asyncpg unix-socket form:
#   postgresql+asyncpg://<user>:<pw>@/<db>?host=/cloudsql/<PROJECT>:<REGION>:<INSTANCE>
# The API reads DATABASE_URL (app_user); the worker reads DATABASE_URL_WORKER
# (worker_user — the cross-tenant claim role). Same drift-honest handling: resource
# + scoped accessor in IaC, value composed + seeded out-of-band per the runbook.

variable "tribunal_database_url_secret_id" {
  description = "Secret Manager secret ID holding the Tribunal API's DATABASE_URL (app_user, asyncpg unix-socket DSN into the `tribunal` schema). Value composed + seeded out-of-band per the runbook (T-13-08)."
  type        = string
  default     = "DATABASE_URL"
}

variable "tribunal_database_url_worker_secret_id" {
  description = "Secret Manager secret ID holding the Tribunal worker's DATABASE_URL_WORKER (worker_user, asyncpg DSN). worker_user is granted USAGE/DML on the `tribunal` schema ONLY (migration 0008, Plan 02) — never `nestor` (isolation firewall, T-13-09). Value seeded out-of-band per the runbook."
  type        = string
  default     = "DATABASE_URL_WORKER"
}

# ---------------------------------------------------- Tribunal audit bucket name secret
variable "tribunal_audit_bucket_secret_id" {
  description = "Secret Manager secret ID holding the AUDIT_GCS_BUCKET name (the bucket audit/gcs_blob.py writes the 7y-retained hash-chain bodies to). Kept as a secret (not a plain env) purely for injection uniformity with the DB/provider secrets; the VALUE is the bucket name, seeded out-of-band per the runbook."
  type        = string
  default     = "AUDIT_GCS_BUCKET"
}

variable "tribunal_audit_bucket_name" {
  description = "Name of the GCS audit-evidence bucket for the Tribunal hash-chain bodies (7y per-object retention, mode=Unlocked — D-09). Default \"\" derives `${var.project}-nestor-audit` in main.tf. Set explicitly to pin a name."
  type        = string
  default     = ""
}

# ================================================================================
# Phase 14 — Auth retirement + integration seam (dedicated SA + seam env)
# ================================================================================
# Phase 14 gives the Tribunal services their OWN least-privilege runtime SA
# (`tribunal-run`, WR-03/D-04b) — distinct from the intake `nestor-run` SA — and
# binds the tribunal-api invoker to ONLY the intake SA (D-04 outer gate). Two new
# variables support that: the dedicated SA's account id, and the non-secret seam
# service URL both the intake tribunal_client and the Tribunal InternalCallerProvider
# read. As with every prior phase these are the INTENDED end-state, INERT until the
# operator runs the § Phase 14 gcloud steps in infra/DEPLOY-RUNBOOK.md (Plan 04).

variable "tribunal_runtime_sa_id" {
  description = "Account ID (local part) for the DEDICATED Tribunal Cloud Run runtime service account (WR-03/D-04b). Distinct from `runtime_sa_id` (the intake `nestor-run` SA): the Tribunal services + migrate Job run as THIS least-privilege SA (cloudsql.client + the six Tribunal secrets + the audit bucket ONLY — no identitytoolkit.admin, no intake superadmin secret, no intake uploads bucket). Making caller SA (nestor-run) != callee SA (tribunal-run) is what makes the tribunal-api invoker gate meaningful."
  type        = string
  default     = "tribunal-run"
}

variable "tribunal_service_url" {
  description = "The tribunal-api Cloud Run service URL WITHOUT a path (e.g. https://tribunal-api-xxxx.run.app). Non-secret. Used verbatim as the OIDC audience: the intake nestor-api's tribunal_client mints an ID token for it, and tribunal-api's InternalCallerProvider verifies its own aud against it. Default \"\" and IaC-drift-inert until the runbook `--update-env-vars TRIBUNAL_SERVICE_URL=...` step (§ Phase 14) captures it from `gcloud run services describe tribunal-api` and sets it live on BOTH services (Pitfall 4 — never guess the URL, never include a path)."
  type        = string
  default     = ""
}
