# Input variables for the Nestor Intake GCP footprint.
#
# Defaults encode the resolved Phase-2 open questions:
#   - region          -> europe-west1 (OQ3: single EU region for the NL/FR/EN base)
#   - tier            -> db-custom-1-3840 (A4: 3.75 GB, default max_connections=100,
#                        comfortably above the D-04 connection-math ceiling of ~30)
#   - db_name         -> nestor (the application database)
#   - allow_unauthenticated -> false (OQ2: authenticated invoker by default; the
#                        deployed /readyz is reached via `gcloud run services proxy`.
#                        Public health-only is an explicit opt-in.)
# image_tag has no default: the deploy is a two-step (apply -> build/push -> apply)
# and the user passes the real tag on the second apply (see infra/README.md).

variable "project" {
  description = "Target GCP project ID."
  type        = string
}

variable "region" {
  description = "GCP region for Cloud SQL, Artifact Registry, and Cloud Run (OQ3)."
  type        = string
  default     = "europe-west1"
}

variable "tier" {
  description = "Cloud SQL machine tier. db-custom-1-3840 -> default max_connections=100 (A4/D-04)."
  type        = string
  default     = "db-custom-1-3840"
}

variable "repo" {
  description = "Artifact Registry Docker repository ID for the backend image."
  type        = string
  default     = "nestor"
}

variable "image_tag" {
  description = "Backend image tag in Artifact Registry (passed on the second apply; see README)."
  type        = string
}

variable "db_name" {
  description = "Cloud SQL application database name."
  type        = string
  default     = "nestor"
}

variable "instance_name" {
  description = "Cloud SQL instance name."
  type        = string
  default     = "nestor-pg"
}

variable "service_name" {
  description = "Cloud Run service name."
  type        = string
  default     = "nestor-api"
}

variable "runtime_sa_id" {
  description = "Account ID (local part) for the Cloud Run runtime service account."
  type        = string
  default     = "nestor-run"
}

variable "superadmin_email" {
  description = "Email of the first superadmin bootstrapped by the nestor-seed-superadmin Cloud Run Job (D-05). The password is supplied at execution time (--update-env-vars SUPERADMIN_PASSWORD=...), never stored in IaC/state (T-03-15)."
  type        = string
  default     = "yanick@agenic.be"
}

variable "superadmin_db_secret_id" {
  description = "Secret Manager secret ID holding the BUILT_IN app_superadmin Cloud SQL user's generated password (Path B / D-05a). This is the SINGLE deliberate stored DB credential — the password is generated by random_password and lives only in Secret Manager; the Cloud Run service env carries the secret RESOURCE NAME (projects/<p>/secrets/<id>/versions/latest), never the value (T-04-16). The app_superadmin user is the EXACT literal the 0003 `current_user='app_superadmin'` bypass policy matches (T-04-20)."
  type        = string
  default     = "nestor-app-superadmin-db-password"
}

variable "allow_unauthenticated" {
  description = "If true, allow public (allUsers) invocation of the Cloud Run service. Default false = authenticated invoker only; verify /readyz via `gcloud run services proxy` (OQ2)."
  type        = bool
  default     = false
}

# ---------------------------------------------------- Frontend origins (WR-02 / Phase 9)
# The browser origin allowlist for the app frontend (Cloudflare Workers / localhost). Used
# BOTH by the Cloud Run CORS middleware (CORS_ALLOWED_ORIGINS env, set out-of-band per the
# runbook) AND by the uploads-bucket CORS policy below: FinalReportBlock / ResearchResultsPanel
# `fetch()` the signed GCS URL directly from the app origin, so `storage.googleapis.com` must
# echo Access-Control-Allow-Origin for these origins or the browser blocks the read (WR-02).
# Default is empty => NO cors block emitted (no broadening); set to the real frontend origins.
variable "cors_allowed_origins" {
  description = "Browser origins allowed to fetch() signed URLs from the uploads bucket (mirror of the Cloud Run CORS_ALLOWED_ORIGINS allowlist). Empty => no bucket CORS policy (WR-02)."
  type        = list(string)
  default     = []
}

# ---------------------------------------------------- AI provider keys (D-07 / Phase 7)
# The LLM (Anthropic) + embedding/Whisper (OpenAI) credentials. Each is a Secret
# Manager secret whose RESOURCE is declared in IaC, but whose VALUE (the version
# payload) is seeded out-of-band per the deploy runbook by default — the key never
# lands in committed IaC/state (T-7-05). The Cloud Run service env injects them
# natively via value_source.secret_key_ref (NOT a runtime access_secret_version
# call) — they have no import-cycle reason to runtime-fetch (unlike the superadmin
# password). The keys are read at call time by the AI seam and are NEVER logged.

variable "anthropic_api_key_secret_id" {
  description = "Secret Manager secret ID holding ANTHROPIC_API_KEY (Anthropic LLM credential, D-07). The secret RESOURCE + the runtime SA's scoped secretAccessor grant are declared in IaC; the VALUE (version payload) is added out-of-band per infra/DEPLOY-RUNBOOK.md (default: no Terraform-managed version), so the key never lands in committed state (T-7-05)."
  type        = string
  default     = "nestor-anthropic-api-key"
}

variable "openai_api_key_secret_id" {
  description = "Secret Manager secret ID holding OPENAI_API_KEY (OpenAI embedding + Whisper credential, D-07). Same handling as anthropic_api_key_secret_id: resource + secretAccessor in IaC, value seeded out-of-band per the runbook (T-7-05)."
  type        = string
  default     = "nestor-openai-api-key"
}

variable "anthropic_api_key" {
  description = "Optional ANTHROPIC_API_KEY VALUE to seed the secret version at apply time. Default \"\" => Terraform creates NO version (add it manually via `gcloud secrets versions add` per DEPLOY-RUNBOOK.md — the drift-honest default). When non-empty the value is written to a secret version and is then in Terraform state, so prefer the manual path in shared environments (T-7-05)."
  type        = string
  default     = ""
  sensitive   = true
}

variable "openai_api_key" {
  description = "Optional OPENAI_API_KEY VALUE to seed the secret version at apply time. Same semantics as anthropic_api_key: default \"\" => no Terraform-managed version (seed manually per the runbook). Non-empty => stored in state, so prefer the manual path (T-7-05)."
  type        = string
  default     = ""
  sensitive   = true
}

# ---------------------------------------------------- Transactional email (D-13 / Phase 10)
# The Resend transactional-email credential — the ONLY new secret Phase 10 adds. The
# `agenic.be` sender domain is already verified. Same drift-honest handling as the AI
# provider keys: the secret RESOURCE + the runtime SA's scoped secretAccessor grant are
# declared in IaC, but the VALUE (version payload) is seeded out-of-band per the deploy
# runbook by default (T-10-04) — the key never lands in committed IaC/state. The Cloud Run
# service env injects it natively via value_source.secret_key_ref; the mail module reads
# RESEND_API_KEY from the process env at call time and must NEVER log it.

variable "resend_api_key_secret_id" {
  description = "Secret Manager secret ID holding RESEND_API_KEY (Resend transactional-email credential, D-13). The secret RESOURCE + the runtime SA's scoped secretAccessor grant are declared in IaC; the VALUE (version payload) is added out-of-band per infra/DEPLOY-RUNBOOK.md (default: no Terraform-managed version), so the key never lands in committed state (T-10-04)."
  type        = string
  default     = "nestor-resend-api-key"
}

variable "resend_api_key" {
  description = "Optional RESEND_API_KEY VALUE to seed the secret version at apply time. Default \"\" => Terraform creates NO version (add it manually via `gcloud secrets versions add` per DEPLOY-RUNBOOK.md — the drift-honest default). When non-empty the value is written to a secret version and is then in Terraform state, so prefer the manual path in shared environments (T-10-04)."
  type        = string
  default     = ""
  sensitive   = true
}

# ---------------------------------------------------- Mail non-secret config (D-08 / Phase 10)
# Two PLAIN (non-secret) Cloud Run env vars the mail module reads at call time:
#   - NESTOR_ADMIN_EMAIL -> Settings.nestor_admin_email (D-08): the ops address that
#     receives the admin_validated notification.
#   - APP_BASE_URL -> Settings.app_base_url: the origin used to build mail CTA links and
#     the logo asset URL (closes the Phase 9 D-07a handoff — no more public Supabase URL).
# Both default "" and are IaC-DRIFT-inert until the runbook `--update-env-vars` step sets
# them live (mirror the STORAGE_BUCKET drift semantics).

variable "nestor_admin_email" {
  description = "Ops address that receives the admin_validated mail notification (D-08 -> Settings.nestor_admin_email). Plain non-secret Cloud Run env; default \"\" and IaC-drift-inert until the runbook `--update-env-vars NESTOR_ADMIN_EMAIL=...` step sets it live (Phase 10)."
  type        = string
  default     = ""
}

variable "app_base_url" {
  description = "Deployed frontend origin used to build mail CTA links + the logo asset URL (-> Settings.app_base_url, D-15). Plain non-secret Cloud Run env; default \"\" and IaC-drift-inert until the runbook `--update-env-vars APP_BASE_URL=...` step sets it live (Phase 10)."
  type        = string
  default     = ""
}
