"""AUTH-05 bearer-route-removal guard — a STRUCTURAL (filesystem) assertion that
the never-expiring bearer-link routes (and the OTP callback) are gone.

D-01 retires the token-link client-access model: login is required for everyone,
email becomes notification-only. This guard fails while any of the five
``*.$token.tsx`` route files (or ``auth.callback.tsx``, the OTP exchange) still
exist, and passes once plan 04 deletes them and regenerates the route tree.

**Wave 0 RED scaffold:** these files still exist today, so the suite is RED until
plan 04 lands. It lives in the BACKEND suite (so it runs in CI alongside the
backend tests) even though it inspects ``frontend/`` files; the repo root is
resolved relative to ``__file__`` — never a hardcoded absolute path. The
route-tree check skips cleanly when ``routeTree.gen.ts`` is absent, mirroring the
conftest skip-clean philosophy.

Authoritative references:
- .planning/phases/03-identity-platform-auth/03-RESEARCH.md
    § Architecture Patterns 6 (the 5 bearer-route files; routeTree.gen.ts is the
      only other reference site) + § Validation Architecture (AUTH-05 row)
- .planning/phases/03-identity-platform-auth/03-PATTERNS.md
    § test_no_bearer_routes.py -- BEARER_ROUTES list + file-absence + gen-tree checks
- D-01 (bearer links removed; login required; email notification-only)
"""

from __future__ import annotations

import os

import pytest

# This file lives at backend/tests/test_no_bearer_routes.py. The repo root is
# three levels up: tests -> backend -> repo root. Derived from __file__ so the
# test is portable (no hardcoded absolute path).
_REPO_ROOT = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)

# The five never-expiring bearer-token route files plus the OTP callback
# (deleted per D-01 — there is no code-exchange step in the login-only model).
BEARER_ROUTES = [
    os.path.join("frontend", "src", "routes", "intake.$token.tsx"),
    os.path.join("frontend", "src", "routes", "results.$token.tsx"),
    os.path.join("frontend", "src", "routes", "sales.intake.$token.tsx"),
    os.path.join("frontend", "src", "routes", "sales.results.$token.tsx"),
    os.path.join("frontend", "src", "routes", "sales.validate.$token.tsx"),
    os.path.join("frontend", "src", "routes", "auth.callback.tsx"),
]

# The corresponding route IDs that TanStack Router bakes into routeTree.gen.ts.
BEARER_ROUTE_IDS = [
    "/intake/$token",
    "/results/$token",
    "/sales/intake/$token",
    "/sales/results/$token",
    "/sales/validate/$token",
    "/auth/callback",
]

_ROUTETREE = os.path.join("frontend", "src", "routeTree.gen.ts")


def test_bearer_route_files_absent():
    """None of the bearer-token route files (nor the OTP callback) may exist.

    RED until plan 04 deletes them; the failure message names every offender so
    the deletion task is unambiguous.
    """
    present = [
        rel for rel in BEARER_ROUTES if os.path.exists(os.path.join(_REPO_ROOT, rel))
    ]
    assert not present, (
        "Bearer-token route files still present (AUTH-05 / D-01 — login-only, no "
        f"bearer links): {present}. Plan 04 must delete these and regenerate the "
        "route tree."
    )


def test_routetree_has_no_bearer_refs():
    """routeTree.gen.ts must reference none of the deleted bearer route IDs.

    Skips cleanly if the generated tree is absent (it is regenerated by the
    frontend build; not always present in a backend-only checkout)."""
    gen_path = os.path.join(_REPO_ROOT, _ROUTETREE)
    if not os.path.exists(gen_path):
        pytest.skip("routeTree.gen.ts not present (frontend build artifact absent)")

    content = open(gen_path, encoding="utf-8").read()
    leaked = [rid for rid in BEARER_ROUTE_IDS if rid in content]
    assert not leaked, (
        "routeTree.gen.ts still references deleted bearer route ids "
        f"{leaked} — regenerate the route tree after deleting the bearer routes."
    )
