/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntakeIndexRouteImport } from './routes/intake.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as IntakeIdRouteImport } from './routes/intake.$id'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthActionRouteImport } from './routes/auth.action'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSpacesRouteImport } from './routes/admin.spaces'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminPulseRouteImport } from './routes/admin.pulse'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminSalesIndexRouteImport } from './routes/admin.sales.index'
import { Route as AdminPulseIndexRouteImport } from './routes/admin.pulse.index'
import { Route as AdminIntakesIndexRouteImport } from './routes/admin.intakes.index'
import { Route as IntakeIdResultsRouteImport } from './routes/intake.$id.results'
import { Route as IntakeIdReportRouteImport } from './routes/intake.$id.report'
import { Route as AdminPulseSearchRouteImport } from './routes/admin.pulse.search'
import { Route as AdminPulseClientsRouteImport } from './routes/admin.pulse.clients'
import { Route as AdminIntakesNewRouteImport } from './routes/admin.intakes.new'
import { Route as AdminIntakesIdRouteImport } from './routes/admin.intakes.$id'
import { Route as AdminFluxComingSoonRouteImport } from './routes/admin.flux.coming-soon'
import { Route as AdminEdgeComingSoonRouteImport } from './routes/admin.edge.coming-soon'
import { Route as AdminEchoComingSoonRouteImport } from './routes/admin.echo.coming-soon'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'
import { Route as AdminSalesProjectsIndexRouteImport } from './routes/admin.sales.projects.index'
import { Route as AdminPulseIntakesIndexRouteImport } from './routes/admin.pulse.intakes.index'
import { Route as AdminSalesProjectsNewRouteImport } from './routes/admin.sales.projects.new'
import { Route as AdminSalesProjectsIdRouteImport } from './routes/admin.sales.projects.$id'
import { Route as AdminPulseIntakesNewRouteImport } from './routes/admin.pulse.intakes.new'
import { Route as AdminPulseIntakesIdRouteImport } from './routes/admin.pulse.intakes.$id'
import { Route as AdminPulseClientsIdRouteImport } from './routes/admin.pulse.clients.$id'
import { Route as AdminPulseRunsRunIdIndexRouteImport } from './routes/admin.pulse.runs.$runId.index'
import { Route as AdminPulseRunsRunIdVerificationRouteImport } from './routes/admin.pulse.runs.$runId.verification'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const IntakeIdRoute = IntakeIdRouteImport.update({
  id: '/intake/$id',
  path: '/intake/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionRoute = AuthActionRouteImport.update({
  id: '/auth/action',
  path: '/auth/action',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpacesRoute = AdminSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPulseRoute = AdminPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesIndexRoute = AdminSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSalesRoute,
} as any)
const AdminPulseIndexRoute = AdminPulseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPulseRoute,
} as any)
const AdminIntakesIndexRoute = AdminIntakesIndexRouteImport.update({
  id: '/intakes/',
  path: '/intakes/',
  getParentRoute: () => AdminRoute,
} as any)
const IntakeIdResultsRoute = IntakeIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => IntakeIdRoute,
} as any)
const IntakeIdReportRoute = IntakeIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => IntakeIdRoute,
} as any)
const AdminPulseSearchRoute = AdminPulseSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminPulseRoute,
} as any)
const AdminPulseClientsRoute = AdminPulseClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminPulseRoute,
} as any)
const AdminIntakesNewRoute = AdminIntakesNewRouteImport.update({
  id: '/intakes/new',
  path: '/intakes/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntakesIdRoute = AdminIntakesIdRouteImport.update({
  id: '/intakes/$id',
  path: '/intakes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFluxComingSoonRoute = AdminFluxComingSoonRouteImport.update({
  id: '/flux/coming-soon',
  path: '/flux/coming-soon',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEdgeComingSoonRoute = AdminEdgeComingSoonRouteImport.update({
  id: '/edge/coming-soon',
  path: '/edge/coming-soon',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEchoComingSoonRoute = AdminEchoComingSoonRouteImport.update({
  id: '/echo/coming-soon',
  path: '/echo/coming-soon',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClientsRoute,
} as any)
const AdminSalesProjectsIndexRoute = AdminSalesProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminSalesRoute,
} as any)
const AdminPulseIntakesIndexRoute = AdminPulseIntakesIndexRouteImport.update({
  id: '/intakes/',
  path: '/intakes/',
  getParentRoute: () => AdminPulseRoute,
} as any)
const AdminSalesProjectsNewRoute = AdminSalesProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AdminSalesRoute,
} as any)
const AdminSalesProjectsIdRoute = AdminSalesProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AdminSalesRoute,
} as any)
const AdminPulseIntakesNewRoute = AdminPulseIntakesNewRouteImport.update({
  id: '/intakes/new',
  path: '/intakes/new',
  getParentRoute: () => AdminPulseRoute,
} as any)
const AdminPulseIntakesIdRoute = AdminPulseIntakesIdRouteImport.update({
  id: '/intakes/$id',
  path: '/intakes/$id',
  getParentRoute: () => AdminPulseRoute,
} as any)
const AdminPulseClientsIdRoute = AdminPulseClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPulseClientsRoute,
} as any)
const AdminPulseRunsRunIdIndexRoute =
  AdminPulseRunsRunIdIndexRouteImport.update({
    id: '/runs/$runId/',
    path: '/runs/$runId/',
    getParentRoute: () => AdminPulseRoute,
  } as any)
const AdminPulseRunsRunIdVerificationRoute =
  AdminPulseRunsRunIdVerificationRouteImport.update({
    id: '/runs/$runId/verification',
    path: '/runs/$runId/verification',
    getParentRoute: () => AdminPulseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/pulse': typeof AdminPulseRouteWithChildren
  '/admin/sales': typeof AdminSalesRouteWithChildren
  '/admin/search': typeof AdminSearchRoute
  '/admin/spaces': typeof AdminSpacesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/action': typeof AuthActionRoute
  '/auth/login': typeof AuthLoginRoute
  '/intake/$id': typeof IntakeIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/intake/': typeof IntakeIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/echo/coming-soon': typeof AdminEchoComingSoonRoute
  '/admin/edge/coming-soon': typeof AdminEdgeComingSoonRoute
  '/admin/flux/coming-soon': typeof AdminFluxComingSoonRoute
  '/admin/intakes/$id': typeof AdminIntakesIdRoute
  '/admin/intakes/new': typeof AdminIntakesNewRoute
  '/admin/pulse/clients': typeof AdminPulseClientsRouteWithChildren
  '/admin/pulse/search': typeof AdminPulseSearchRoute
  '/intake/$id/report': typeof IntakeIdReportRoute
  '/intake/$id/results': typeof IntakeIdResultsRoute
  '/admin/intakes/': typeof AdminIntakesIndexRoute
  '/admin/pulse/': typeof AdminPulseIndexRoute
  '/admin/sales/': typeof AdminSalesIndexRoute
  '/admin/pulse/clients/$id': typeof AdminPulseClientsIdRoute
  '/admin/pulse/intakes/$id': typeof AdminPulseIntakesIdRoute
  '/admin/pulse/intakes/new': typeof AdminPulseIntakesNewRoute
  '/admin/sales/projects/$id': typeof AdminSalesProjectsIdRoute
  '/admin/sales/projects/new': typeof AdminSalesProjectsNewRoute
  '/admin/pulse/intakes/': typeof AdminPulseIntakesIndexRoute
  '/admin/sales/projects/': typeof AdminSalesProjectsIndexRoute
  '/admin/pulse/runs/$runId/verification': typeof AdminPulseRunsRunIdVerificationRoute
  '/admin/pulse/runs/$runId/': typeof AdminPulseRunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/spaces': typeof AdminSpacesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/action': typeof AuthActionRoute
  '/auth/login': typeof AuthLoginRoute
  '/intake/$id': typeof IntakeIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/intake': typeof IntakeIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/echo/coming-soon': typeof AdminEchoComingSoonRoute
  '/admin/edge/coming-soon': typeof AdminEdgeComingSoonRoute
  '/admin/flux/coming-soon': typeof AdminFluxComingSoonRoute
  '/admin/intakes/$id': typeof AdminIntakesIdRoute
  '/admin/intakes/new': typeof AdminIntakesNewRoute
  '/admin/pulse/clients': typeof AdminPulseClientsRouteWithChildren
  '/admin/pulse/search': typeof AdminPulseSearchRoute
  '/intake/$id/report': typeof IntakeIdReportRoute
  '/intake/$id/results': typeof IntakeIdResultsRoute
  '/admin/intakes': typeof AdminIntakesIndexRoute
  '/admin/pulse': typeof AdminPulseIndexRoute
  '/admin/sales': typeof AdminSalesIndexRoute
  '/admin/pulse/clients/$id': typeof AdminPulseClientsIdRoute
  '/admin/pulse/intakes/$id': typeof AdminPulseIntakesIdRoute
  '/admin/pulse/intakes/new': typeof AdminPulseIntakesNewRoute
  '/admin/sales/projects/$id': typeof AdminSalesProjectsIdRoute
  '/admin/sales/projects/new': typeof AdminSalesProjectsNewRoute
  '/admin/pulse/intakes': typeof AdminPulseIntakesIndexRoute
  '/admin/sales/projects': typeof AdminSalesProjectsIndexRoute
  '/admin/pulse/runs/$runId/verification': typeof AdminPulseRunsRunIdVerificationRoute
  '/admin/pulse/runs/$runId': typeof AdminPulseRunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/pulse': typeof AdminPulseRouteWithChildren
  '/admin/sales': typeof AdminSalesRouteWithChildren
  '/admin/search': typeof AdminSearchRoute
  '/admin/spaces': typeof AdminSpacesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/action': typeof AuthActionRoute
  '/auth/login': typeof AuthLoginRoute
  '/intake/$id': typeof IntakeIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/intake/': typeof IntakeIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/echo/coming-soon': typeof AdminEchoComingSoonRoute
  '/admin/edge/coming-soon': typeof AdminEdgeComingSoonRoute
  '/admin/flux/coming-soon': typeof AdminFluxComingSoonRoute
  '/admin/intakes/$id': typeof AdminIntakesIdRoute
  '/admin/intakes/new': typeof AdminIntakesNewRoute
  '/admin/pulse/clients': typeof AdminPulseClientsRouteWithChildren
  '/admin/pulse/search': typeof AdminPulseSearchRoute
  '/intake/$id/report': typeof IntakeIdReportRoute
  '/intake/$id/results': typeof IntakeIdResultsRoute
  '/admin/intakes/': typeof AdminIntakesIndexRoute
  '/admin/pulse/': typeof AdminPulseIndexRoute
  '/admin/sales/': typeof AdminSalesIndexRoute
  '/admin/pulse/clients/$id': typeof AdminPulseClientsIdRoute
  '/admin/pulse/intakes/$id': typeof AdminPulseIntakesIdRoute
  '/admin/pulse/intakes/new': typeof AdminPulseIntakesNewRoute
  '/admin/sales/projects/$id': typeof AdminSalesProjectsIdRoute
  '/admin/sales/projects/new': typeof AdminSalesProjectsNewRoute
  '/admin/pulse/intakes/': typeof AdminPulseIntakesIndexRoute
  '/admin/sales/projects/': typeof AdminSalesProjectsIndexRoute
  '/admin/pulse/runs/$runId/verification': typeof AdminPulseRunsRunIdVerificationRoute
  '/admin/pulse/runs/$runId/': typeof AdminPulseRunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/clients'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/pulse'
    | '/admin/sales'
    | '/admin/search'
    | '/admin/spaces'
    | '/admin/users'
    | '/auth/action'
    | '/auth/login'
    | '/intake/$id'
    | '/admin/'
    | '/intake/'
    | '/admin/clients/$id'
    | '/admin/echo/coming-soon'
    | '/admin/edge/coming-soon'
    | '/admin/flux/coming-soon'
    | '/admin/intakes/$id'
    | '/admin/intakes/new'
    | '/admin/pulse/clients'
    | '/admin/pulse/search'
    | '/intake/$id/report'
    | '/intake/$id/results'
    | '/admin/intakes/'
    | '/admin/pulse/'
    | '/admin/sales/'
    | '/admin/pulse/clients/$id'
    | '/admin/pulse/intakes/$id'
    | '/admin/pulse/intakes/new'
    | '/admin/sales/projects/$id'
    | '/admin/sales/projects/new'
    | '/admin/pulse/intakes/'
    | '/admin/sales/projects/'
    | '/admin/pulse/runs/$runId/verification'
    | '/admin/pulse/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/clients'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/search'
    | '/admin/spaces'
    | '/admin/users'
    | '/auth/action'
    | '/auth/login'
    | '/intake/$id'
    | '/admin'
    | '/intake'
    | '/admin/clients/$id'
    | '/admin/echo/coming-soon'
    | '/admin/edge/coming-soon'
    | '/admin/flux/coming-soon'
    | '/admin/intakes/$id'
    | '/admin/intakes/new'
    | '/admin/pulse/clients'
    | '/admin/pulse/search'
    | '/intake/$id/report'
    | '/intake/$id/results'
    | '/admin/intakes'
    | '/admin/pulse'
    | '/admin/sales'
    | '/admin/pulse/clients/$id'
    | '/admin/pulse/intakes/$id'
    | '/admin/pulse/intakes/new'
    | '/admin/sales/projects/$id'
    | '/admin/sales/projects/new'
    | '/admin/pulse/intakes'
    | '/admin/sales/projects'
    | '/admin/pulse/runs/$runId/verification'
    | '/admin/pulse/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/clients'
    | '/admin/login'
    | '/admin/organizations'
    | '/admin/pulse'
    | '/admin/sales'
    | '/admin/search'
    | '/admin/spaces'
    | '/admin/users'
    | '/auth/action'
    | '/auth/login'
    | '/intake/$id'
    | '/admin/'
    | '/intake/'
    | '/admin/clients/$id'
    | '/admin/echo/coming-soon'
    | '/admin/edge/coming-soon'
    | '/admin/flux/coming-soon'
    | '/admin/intakes/$id'
    | '/admin/intakes/new'
    | '/admin/pulse/clients'
    | '/admin/pulse/search'
    | '/intake/$id/report'
    | '/intake/$id/results'
    | '/admin/intakes/'
    | '/admin/pulse/'
    | '/admin/sales/'
    | '/admin/pulse/clients/$id'
    | '/admin/pulse/intakes/$id'
    | '/admin/pulse/intakes/new'
    | '/admin/sales/projects/$id'
    | '/admin/sales/projects/new'
    | '/admin/pulse/intakes/'
    | '/admin/sales/projects/'
    | '/admin/pulse/runs/$runId/verification'
    | '/admin/pulse/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthActionRoute: typeof AuthActionRoute
  AuthLoginRoute: typeof AuthLoginRoute
  IntakeIdRoute: typeof IntakeIdRouteWithChildren
  IntakeIndexRoute: typeof IntakeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/intake/$id': {
      id: '/intake/$id'
      path: '/intake/$id'
      fullPath: '/intake/$id'
      preLoaderRoute: typeof IntakeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/action': {
      id: '/auth/action'
      path: '/auth/action'
      fullPath: '/auth/action'
      preLoaderRoute: typeof AuthActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/spaces': {
      id: '/admin/spaces'
      path: '/spaces'
      fullPath: '/admin/spaces'
      preLoaderRoute: typeof AdminSpacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pulse': {
      id: '/admin/pulse'
      path: '/pulse'
      fullPath: '/admin/pulse'
      preLoaderRoute: typeof AdminPulseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales/': {
      id: '/admin/sales/'
      path: '/'
      fullPath: '/admin/sales/'
      preLoaderRoute: typeof AdminSalesIndexRouteImport
      parentRoute: typeof AdminSalesRoute
    }
    '/admin/pulse/': {
      id: '/admin/pulse/'
      path: '/'
      fullPath: '/admin/pulse/'
      preLoaderRoute: typeof AdminPulseIndexRouteImport
      parentRoute: typeof AdminPulseRoute
    }
    '/admin/intakes/': {
      id: '/admin/intakes/'
      path: '/intakes'
      fullPath: '/admin/intakes/'
      preLoaderRoute: typeof AdminIntakesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/intake/$id/results': {
      id: '/intake/$id/results'
      path: '/results'
      fullPath: '/intake/$id/results'
      preLoaderRoute: typeof IntakeIdResultsRouteImport
      parentRoute: typeof IntakeIdRoute
    }
    '/intake/$id/report': {
      id: '/intake/$id/report'
      path: '/report'
      fullPath: '/intake/$id/report'
      preLoaderRoute: typeof IntakeIdReportRouteImport
      parentRoute: typeof IntakeIdRoute
    }
    '/admin/pulse/search': {
      id: '/admin/pulse/search'
      path: '/search'
      fullPath: '/admin/pulse/search'
      preLoaderRoute: typeof AdminPulseSearchRouteImport
      parentRoute: typeof AdminPulseRoute
    }
    '/admin/pulse/clients': {
      id: '/admin/pulse/clients'
      path: '/clients'
      fullPath: '/admin/pulse/clients'
      preLoaderRoute: typeof AdminPulseClientsRouteImport
      parentRoute: typeof AdminPulseRoute
    }
    '/admin/intakes/new': {
      id: '/admin/intakes/new'
      path: '/intakes/new'
      fullPath: '/admin/intakes/new'
      preLoaderRoute: typeof AdminIntakesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intakes/$id': {
      id: '/admin/intakes/$id'
      path: '/intakes/$id'
      fullPath: '/admin/intakes/$id'
      preLoaderRoute: typeof AdminIntakesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flux/coming-soon': {
      id: '/admin/flux/coming-soon'
      path: '/flux/coming-soon'
      fullPath: '/admin/flux/coming-soon'
      preLoaderRoute: typeof AdminFluxComingSoonRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edge/coming-soon': {
      id: '/admin/edge/coming-soon'
      path: '/edge/coming-soon'
      fullPath: '/admin/edge/coming-soon'
      preLoaderRoute: typeof AdminEdgeComingSoonRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/echo/coming-soon': {
      id: '/admin/echo/coming-soon'
      path: '/echo/coming-soon'
      fullPath: '/admin/echo/coming-soon'
      preLoaderRoute: typeof AdminEchoComingSoonRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminClientsRoute
    }
    '/admin/sales/projects/': {
      id: '/admin/sales/projects/'
      path: '/projects'
      fullPath: '/admin/sales/projects/'
      preLoaderRoute: typeof AdminSalesProjectsIndexRouteImport
      parentRoute: typeof AdminSalesRoute
    }
    '/admin/pulse/intakes/': {
      id: '/admin/pulse/intakes/'
      path: '/intakes'
      fullPath: '/admin/pulse/intakes/'
      preLoaderRoute: typeof AdminPulseIntakesIndexRouteImport
      parentRoute: typeof AdminPulseRoute
    }
    '/admin/sales/projects/new': {
      id: '/admin/sales/projects/new'
      path: '/projects/new'
      fullPath: '/admin/sales/projects/new'
      preLoaderRoute: typeof AdminSalesProjectsNewRouteImport
      parentRoute: typeof AdminSalesRoute
    }
    '/admin/sales/projects/$id': {
      id: '/admin/sales/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/sales/projects/$id'
      preLoaderRoute: typeof AdminSalesProjectsIdRouteImport
      parentRoute: typeof AdminSalesRoute
    }
    '/admin/pulse/intakes/new': {
      id: '/admin/pulse/intakes/new'
      path: '/intakes/new'
      fullPath: '/admin/pulse/intakes/new'
      preLoaderRoute: typeof AdminPulseIntakesNewRouteImport
      parentRoute: typeof AdminPulseRoute
    }
    '/admin/pulse/intakes/$id': {
      id: '/admin/pulse/intakes/$id'
      path: '/intakes/$id'
      fullPath: '/admin/pulse/intakes/$id'
      preLoaderRoute: typeof AdminPulseIntakesIdRouteImport
      parentRoute: typeof AdminPulseRoute
    }
    '/admin/pulse/clients/$id': {
      id: '/admin/pulse/clients/$id'
      path: '/$id'
      fullPath: '/admin/pulse/clients/$id'
      preLoaderRoute: typeof AdminPulseClientsIdRouteImport
      parentRoute: typeof AdminPulseClientsRoute
    }
    '/admin/pulse/runs/$runId/': {
      id: '/admin/pulse/runs/$runId/'
      path: '/runs/$runId'
      fullPath: '/admin/pulse/runs/$runId/'
      preLoaderRoute: typeof AdminPulseRunsRunIdIndexRouteImport
      parentRoute: typeof AdminPulseRoute
    }
    '/admin/pulse/runs/$runId/verification': {
      id: '/admin/pulse/runs/$runId/verification'
      path: '/runs/$runId/verification'
      fullPath: '/admin/pulse/runs/$runId/verification'
      preLoaderRoute: typeof AdminPulseRunsRunIdVerificationRouteImport
      parentRoute: typeof AdminPulseRoute
    }
  }
}

interface AdminClientsRouteChildren {
  AdminClientsIdRoute: typeof AdminClientsIdRoute
}

const AdminClientsRouteChildren: AdminClientsRouteChildren = {
  AdminClientsIdRoute: AdminClientsIdRoute,
}

const AdminClientsRouteWithChildren = AdminClientsRoute._addFileChildren(
  AdminClientsRouteChildren,
)

interface AdminPulseClientsRouteChildren {
  AdminPulseClientsIdRoute: typeof AdminPulseClientsIdRoute
}

const AdminPulseClientsRouteChildren: AdminPulseClientsRouteChildren = {
  AdminPulseClientsIdRoute: AdminPulseClientsIdRoute,
}

const AdminPulseClientsRouteWithChildren =
  AdminPulseClientsRoute._addFileChildren(AdminPulseClientsRouteChildren)

interface AdminPulseRouteChildren {
  AdminPulseClientsRoute: typeof AdminPulseClientsRouteWithChildren
  AdminPulseSearchRoute: typeof AdminPulseSearchRoute
  AdminPulseIndexRoute: typeof AdminPulseIndexRoute
  AdminPulseIntakesIdRoute: typeof AdminPulseIntakesIdRoute
  AdminPulseIntakesNewRoute: typeof AdminPulseIntakesNewRoute
  AdminPulseIntakesIndexRoute: typeof AdminPulseIntakesIndexRoute
  AdminPulseRunsRunIdVerificationRoute: typeof AdminPulseRunsRunIdVerificationRoute
  AdminPulseRunsRunIdIndexRoute: typeof AdminPulseRunsRunIdIndexRoute
}

const AdminPulseRouteChildren: AdminPulseRouteChildren = {
  AdminPulseClientsRoute: AdminPulseClientsRouteWithChildren,
  AdminPulseSearchRoute: AdminPulseSearchRoute,
  AdminPulseIndexRoute: AdminPulseIndexRoute,
  AdminPulseIntakesIdRoute: AdminPulseIntakesIdRoute,
  AdminPulseIntakesNewRoute: AdminPulseIntakesNewRoute,
  AdminPulseIntakesIndexRoute: AdminPulseIntakesIndexRoute,
  AdminPulseRunsRunIdVerificationRoute: AdminPulseRunsRunIdVerificationRoute,
  AdminPulseRunsRunIdIndexRoute: AdminPulseRunsRunIdIndexRoute,
}

const AdminPulseRouteWithChildren = AdminPulseRoute._addFileChildren(
  AdminPulseRouteChildren,
)

interface AdminSalesRouteChildren {
  AdminSalesIndexRoute: typeof AdminSalesIndexRoute
  AdminSalesProjectsIdRoute: typeof AdminSalesProjectsIdRoute
  AdminSalesProjectsNewRoute: typeof AdminSalesProjectsNewRoute
  AdminSalesProjectsIndexRoute: typeof AdminSalesProjectsIndexRoute
}

const AdminSalesRouteChildren: AdminSalesRouteChildren = {
  AdminSalesIndexRoute: AdminSalesIndexRoute,
  AdminSalesProjectsIdRoute: AdminSalesProjectsIdRoute,
  AdminSalesProjectsNewRoute: AdminSalesProjectsNewRoute,
  AdminSalesProjectsIndexRoute: AdminSalesProjectsIndexRoute,
}

const AdminSalesRouteWithChildren = AdminSalesRoute._addFileChildren(
  AdminSalesRouteChildren,
)

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminPulseRoute: typeof AdminPulseRouteWithChildren
  AdminSalesRoute: typeof AdminSalesRouteWithChildren
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSpacesRoute: typeof AdminSpacesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEchoComingSoonRoute: typeof AdminEchoComingSoonRoute
  AdminEdgeComingSoonRoute: typeof AdminEdgeComingSoonRoute
  AdminFluxComingSoonRoute: typeof AdminFluxComingSoonRoute
  AdminIntakesIdRoute: typeof AdminIntakesIdRoute
  AdminIntakesNewRoute: typeof AdminIntakesNewRoute
  AdminIntakesIndexRoute: typeof AdminIntakesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminPulseRoute: AdminPulseRouteWithChildren,
  AdminSalesRoute: AdminSalesRouteWithChildren,
  AdminSearchRoute: AdminSearchRoute,
  AdminSpacesRoute: AdminSpacesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEchoComingSoonRoute: AdminEchoComingSoonRoute,
  AdminEdgeComingSoonRoute: AdminEdgeComingSoonRoute,
  AdminFluxComingSoonRoute: AdminFluxComingSoonRoute,
  AdminIntakesIdRoute: AdminIntakesIdRoute,
  AdminIntakesNewRoute: AdminIntakesNewRoute,
  AdminIntakesIndexRoute: AdminIntakesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface IntakeIdRouteChildren {
  IntakeIdReportRoute: typeof IntakeIdReportRoute
  IntakeIdResultsRoute: typeof IntakeIdResultsRoute
}

const IntakeIdRouteChildren: IntakeIdRouteChildren = {
  IntakeIdReportRoute: IntakeIdReportRoute,
  IntakeIdResultsRoute: IntakeIdResultsRoute,
}

const IntakeIdRouteWithChildren = IntakeIdRoute._addFileChildren(
  IntakeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthActionRoute: AuthActionRoute,
  AuthLoginRoute: AuthLoginRoute,
  IntakeIdRoute: IntakeIdRouteWithChildren,
  IntakeIndexRoute: IntakeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
