"""The rendered `## Sources` list: mechanism 4 of the run-7784e71c defect.

WHY. On run `7784e71c` the reader was handed 66 opaque
`vertexaisearch.cloud.google.com/grounding-api-redirect/...` links. 21 of the 27
redirects in that run HAD ALREADY BEEN RESOLVED to their publisher URL and the
target was sitting in `source.resolved_url` (D-V01-11) — the renderer simply
never read the column. The redirect is also not durable: it expires roughly 30
days after the run, so the delivered report ships links that are opaque today
and dead next month.

THE FLAGS-OFF ARM IS THE POINT OF THIS FILE. `golden_sources_flags_off.md` was
generated by running `build_graded_sources_section` from code NOBODY HAD EDITED
(commit `a4d2dda`, the plan's base) over `make_numbered_entries()` + `PROSE`, and
committed BEFORE the first edit to `steps.py`. It is therefore a real comparison
rather than a restatement of whatever the function does now. `git log --` on the
golden and on `steps.py` shows the order.

The same entry list is valid on BOTH sides of the change: HEAD ignored the extra
`resolved_url` key entirely, which is what lets one fixture serve as both the
golden input and the flags-on input.

ZERO LLM calls, zero network, zero database, no mocking library — the house
conventions of `test_report_sections.py`. These are pure functions.

Coverage:
  1     the flags-off golden, asserted as a WHOLE-STRING equality
  2-3   byte-stability across two renders, on both flag paths
  4     flags ON: not one rendered line carries a redirect host for an entry
        that has a `resolved_url` (the CONTEXT's acceptance number: 0)
  5     flags ON: an UNRESOLVED redirect still renders — a citation is never
        dropped for failing to resolve
  6-7   flags ON: the label is the stored title when there is one, and the
        RESOLVED url's display domain when there is not — never the redirect host
  8     flags ON: the append-only prose rescue lists a document under neither its
        redirect nor its resolved form once it is numbered
  9     an entry with no url at all still renders, as plain text
 10-11  the key may be absent, None or empty — none of the three may raise or
        blank out a link
 12     the sub-switch alone changes nothing while the master is off
"""
from __future__ import annotations

import pathlib

import pytest

from nestor_pulse_sdk.pipeline.synthesis.steps import build_graded_sources_section

# ---------------------------------------------------------------------------
# The fixture. Plain literals, built by a FUNCTION so a test can re-create
# identical input and prove the output does not depend on object identity
# (test_report_sections.py's convention).
#
# SYNTHETIC SHAPES, NOT COPIED ROWS. Nothing here came out of a database and no
# value is production text; each entry reproduces a shape measured on run
# 7784e71c and recorded in the phase CONTEXT.
# ---------------------------------------------------------------------------

REDIRECT_HOST = "vertexaisearch.cloud.google.com"
REDIRECT_RESOLVED = f"https://{REDIRECT_HOST}/grounding-api-redirect/AbCdEf-resolved"
REDIRECT_UNRESOLVED = f"https://{REDIRECT_HOST}/grounding-api-redirect/GhIjKl-unresolved"
REDIRECT_NO_TITLE = f"https://{REDIRECT_HOST}/grounding-api-redirect/MnOpQr-notitle"

RESOLVED_TARGET = "https://www.cbs.nl/nl-nl/cijfers/fixture-table"
RESOLVED_TARGET_NO_TITLE = "https://www.rijksoverheid.nl/onderwerpen/fixture"

EXTRA_PROSE_URL = "https://blog.example.com/fixture-extra"


def make_numbered_entries() -> list[dict]:
    """One entry per shape the renderer has to survive."""
    return [
        # 1. a plain publisher url, fully labelled. `resolved_url` is None
        #    because a non-redirect is never resolved.
        {
            "n": 1,
            "url": "https://www.nos.nl/artikel/2500001-fixture-article",
            "title": "NOS — fixture article",
            "quality_tier": 2,
            "publication_date": "2026-03-04T10:11:12+00:00",
            "single_source": False,
            "resolved_url": None,
        },
        # 2. a grounding redirect that RESOLVED, with a stored title.
        {
            "n": 2,
            "url": REDIRECT_RESOLVED,
            "title": "CBS — fixture table",
            "quality_tier": 1,
            "publication_date": "2026-02-01T00:00:00+00:00",
            "single_source": True,
            "resolved_url": RESOLVED_TARGET,
        },
        # 3. a grounding redirect whose resolution was ATTEMPTED and FAILED.
        #    It must still be rendered — never dropped.
        {
            "n": 3,
            "url": REDIRECT_UNRESOLVED,
            "title": None,
            "quality_tier": 3,
            "publication_date": None,
            "single_source": False,
            "resolved_url": None,
        },
        # 4. a RESOLVED redirect with NO stored title: the label has to come
        #    from the resolved url's own display domain.
        {
            "n": 4,
            "url": REDIRECT_NO_TITLE,
            "title": None,
            "quality_tier": None,
            "publication_date": "2026-01-15",
            "single_source": False,
            "resolved_url": RESOLVED_TARGET_NO_TITLE,
        },
        # 5. no url at all (the plain-text branch).
        {
            "n": 5,
            "url": None,
            "title": "A source with no usable url",
            "quality_tier": 2,
            "publication_date": None,
            "single_source": True,
            "resolved_url": None,
        },
        # 6. `resolved_url` present but EMPTY — the shape a failed resolution
        #    can also take. Must fall back to `url`, not to a blank link.
        {
            "n": 6,
            "url": "https://www.ft.com/content/fixture-6",
            "title": "FT — fixture 6",
            "quality_tier": 2,
            "publication_date": "2025-12-31T23:59:59+00:00",
            "single_source": False,
            "resolved_url": "",
        },
        # 7. the key is ABSENT ENTIRELY. This is the flags-off entry shape plan
        #    05 actually ships (`include_resolved=False` adds no key at all), so
        #    the renderer must use `.get`, never `[...]`.
        {
            "n": 7,
            "url": "https://example.gov/fixture-7",
            "title": "Example Gov — fixture 7",
            "quality_tier": 1,
            "publication_date": None,
            "single_source": False,
        },
    ]


#: Report prose handed to the renderer. It cites entry 2 under BOTH spellings —
#: the redirect the model was given and the publisher url it resolves to — plus
#: one link that is in no numbered entry, which the append-only rescue must
#: still list.
PROSE = (
    "Body text citing [CBS](" + REDIRECT_RESOLVED + ") and the same document "
    "again as [CBS](" + RESOLVED_TARGET + "), plus an unnumbered "
    "[blog post](" + EXTRA_PROSE_URL + ")."
)

GOLDEN_PATH = (
    pathlib.Path(__file__).resolve().parent
    / "fixtures"
    / "citations_replay"
    / "golden_sources_flags_off.md"
)

#: Read in TEXT mode on purpose: `core.autocrlf` is `true` in this repo, so the
#: committed LF file is CRLF in a Windows working tree and LF in a Cloud Build
#: container. Universal-newline translation makes the two identical here, which
#: is the only difference the comparison must not see.
GOLDEN = GOLDEN_PATH.read_text(encoding="utf-8")


@pytest.fixture
def flags_off(monkeypatch):
    """Today's shipped default: the master unset, every sub-switch unset."""
    for name in (
        "NESTOR_CITATIONS_V2",
        "NESTOR_CITATIONS_RENDER_RESOLVED",
    ):
        monkeypatch.delenv(name, raising=False)


@pytest.fixture
def flags_on(monkeypatch):
    """The master on; `render_resolved` takes its documented `true` default."""
    monkeypatch.setenv("NESTOR_CITATIONS_V2", "true")
    monkeypatch.delenv("NESTOR_CITATIONS_RENDER_RESOLVED", raising=False)


def _rendered_lines(out: str) -> list[str]:
    return [line for line in out.splitlines() if line.strip()]


# ---------------------------------------------------------------------------
# 1-3. The golden, and byte-stability on both paths.
# ---------------------------------------------------------------------------


def test_flags_off_output_is_byte_identical_to_the_unmodified_golden(flags_off):
    """THE REVERT ARM.

    The golden was produced by code that had never been edited. If this fails,
    the shipped default is no longer today's behaviour and the kill switch is
    not a kill switch.
    """
    rendered = build_graded_sources_section(make_numbered_entries(), PROSE)
    assert rendered == GOLDEN


def test_two_renders_are_byte_identical_with_the_flags_off(flags_off):
    a = build_graded_sources_section(make_numbered_entries(), PROSE)
    b = build_graded_sources_section(make_numbered_entries(), PROSE)
    assert a == b


def test_two_renders_are_byte_identical_with_the_flags_on(flags_on):
    a = build_graded_sources_section(make_numbered_entries(), PROSE)
    b = build_graded_sources_section(make_numbered_entries(), PROSE)
    assert a == b


# ---------------------------------------------------------------------------
# 4-8. The flags-on behaviours.
# ---------------------------------------------------------------------------


def test_no_line_renders_a_redirect_for_an_entry_that_was_resolved(flags_on):
    """THE ACCEPTANCE NUMBER: "numbered redirect urls rendered opaque while
    resolved_url exists = 0" (phase CONTEXT § Remark 2).

    Asserted as an EMPTY VIOLATIONS LIST rather than a substring check, so the
    failure message names every offending line instead of the first one.
    """
    rendered = build_graded_sources_section(make_numbered_entries(), PROSE)
    resolved_targets = {
        REDIRECT_RESOLVED: RESOLVED_TARGET,
        REDIRECT_NO_TITLE: RESOLVED_TARGET_NO_TITLE,
    }

    violations = []
    for line in _rendered_lines(rendered):
        for redirect in resolved_targets:
            if redirect in line:
                violations.append(line)

    assert violations == []
    # And the positive half: both publisher urls are actually there.
    for target in resolved_targets.values():
        assert f"({target})" in rendered


def test_an_unresolved_redirect_still_renders(flags_on):
    """A citation is NEVER dropped for failing to resolve. The opaque link is
    worse than a publisher link; it is much better than no source at all."""
    rendered = build_graded_sources_section(make_numbered_entries(), PROSE)
    assert f"3. [{REDIRECT_HOST}]({REDIRECT_UNRESOLVED})" in rendered


def test_a_resolved_entry_keeps_its_stored_title_as_the_label(flags_on):
    rendered = build_graded_sources_section(make_numbered_entries(), PROSE)
    assert f"2. [CBS — fixture table]({RESOLVED_TARGET})" in rendered


def test_a_resolved_entry_without_a_title_is_labelled_by_the_resolved_domain(flags_on):
    """`rijksoverheid.nl`, not `vertexaisearch.cloud.google.com`. The label is
    the second place the redirect leaked into the delivered report."""
    rendered = build_graded_sources_section(make_numbered_entries(), PROSE)
    assert f"4. [rijksoverheid.nl]({RESOLVED_TARGET_NO_TITLE})" in rendered
    assert REDIRECT_HOST not in rendered.split("\n4. ")[1].split("\n")[0]


def test_the_prose_rescue_lists_a_numbered_document_under_neither_spelling(flags_on):
    """Entry 2 appears in the prose as BOTH the redirect and the resolved url.
    Neither may come back as an unnumbered extra: that would show the reader the
    same document twice, once under a link the fix exists to stop printing."""
    rendered = build_graded_sources_section(make_numbered_entries(), PROSE)
    _, _, extras = rendered.partition("carry no verified claim link")
    assert REDIRECT_RESOLVED not in extras
    assert RESOLVED_TARGET not in extras
    # The genuinely unnumbered link is still rescued — the append-only promise.
    assert EXTRA_PROSE_URL in extras


# ---------------------------------------------------------------------------
# 9-12. Shapes that must not raise, and the master's reach.
# ---------------------------------------------------------------------------


def test_an_entry_with_no_url_renders_as_plain_text_on_both_paths(monkeypatch):
    for master in ("false", "true"):
        monkeypatch.setenv("NESTOR_CITATIONS_V2", master)
        rendered = build_graded_sources_section(make_numbered_entries(), PROSE)
        assert "5. A source with no usable url — established press" in rendered
        assert "[A source with no usable url]" not in rendered


def test_an_absent_or_empty_resolved_url_falls_back_to_the_url(flags_on):
    """Entry 6 carries `""` and entry 7 carries no key at all. Plan 05 ships the
    absent shape on the flags-off path, so `[...]` here would be a KeyError in
    production the first time an operator flipped the master with stale rows."""
    rendered = build_graded_sources_section(make_numbered_entries(), PROSE)
    assert "6. [FT — fixture 6](https://www.ft.com/content/fixture-6)" in rendered
    assert "7. [Example Gov — fixture 7](https://example.gov/fixture-7)" in rendered


def test_the_sub_switch_alone_does_nothing_while_the_master_is_off(monkeypatch):
    """The AND is the operator's guarantee (runtime_flags module docstring)."""
    monkeypatch.delenv("NESTOR_CITATIONS_V2", raising=False)
    monkeypatch.setenv("NESTOR_CITATIONS_RENDER_RESOLVED", "true")
    assert build_graded_sources_section(make_numbered_entries(), PROSE) == GOLDEN


def test_the_master_on_with_the_sub_switch_off_is_also_the_golden(monkeypatch):
    """The bisect lever: one variable reverts this mechanism alone without
    reverting the rest of the phase."""
    monkeypatch.setenv("NESTOR_CITATIONS_V2", "true")
    monkeypatch.setenv("NESTOR_CITATIONS_RENDER_RESOLVED", "false")
    assert build_graded_sources_section(make_numbered_entries(), PROSE) == GOLDEN


def test_no_numbering_data_still_falls_back_to_the_link_scrape(flags_on):
    """The `if not numbered` path is untouched by this plan: with the master ON
    and no numbering, the output is still the link-scraped list."""
    rendered = build_graded_sources_section(None, PROSE)
    assert rendered.startswith("## Sources\n\n*   [")
    assert REDIRECT_RESOLVED in rendered
